/**
 * File: pinyin_detector.ts
 * Purpose: Detect leftover pinyin/romanized Chinese terms in Vietnamese text
 * Layer: Application (Service)
 * Domain: AdaptationStudio → [Translation Workshop, pinyin detection]
 */

import type { AdaptationScanIssue } from '../../types/adaptation_studio';

export const PINYIN_DICT: Record<string, string> = {
  'dantian': 'đan điền',
  'qi': 'khí',
  'lingqi': 'linh khí',
  'zhenqi': 'chân khí',
  'neili': 'nội lực',
  'neigong': 'nội công',
  'waigong': 'ngoại công',
  'gongfa': 'công pháp',
  'gongli': 'công lực',
  'xiuwei': 'tu vi',
  'xiulian': 'tu luyện',
  'xiuxian': 'tu tiên',
  'xiuzhen': 'tu chân',
  'jingmai': 'kinh mạch',
  'jindan': 'kim đan',
  'yuanying': 'nguyên anh',
  'huashen': 'hóa thần',
  'dujie': 'độ kiếp',
  'lianqi': 'luyện khí',
  'zhuji': 'trúc cơ',
  'jiedan': 'kết đan',
  'yuanshen': 'nguyên thần',
  'shenti': 'thân thể',
  'lingen': 'linh căn',
  'lingshi': 'linh thạch',
  'lingdan': 'linh đan',
  'lingbao': 'linh bảo',
  'lingli': 'linh lực',
  'lingyu': 'linh vực',
  'lingwen': 'linh văn',
  'lingya': 'linh nha',
  'lingquan': 'linh tuyền',
  'lingmai': 'linh mạch',
  'lingjie': 'linh giới',
  'lingzhi': 'linh chi',
  'tianjie': 'thiên kiếp',
  'tiandao': 'thiên đạo',
  'tianming': 'thiên mệnh',
  'tianfu': 'thiên phú',
  'tiancai': 'thiên tài',
  'daoji': 'đạo cơ',
  'daoxin': 'đạo tâm',
  'daoyun': 'đạo vận',
  'wuxing': 'ngũ hành',
  'yinyang': 'âm dương',
  'bagua': 'bát quái',
  'taiji': 'thái cực',
  'wuji': 'vô cực',
  'hundun': 'hỗn độn',
  'shenshi': 'thần thức',
  'shenhun': 'thần hồn',
  'shennian': 'thần niệm',
  'shenli': 'thần lực',
  'moqi': 'ma khí',
  'moli': 'ma lực',
  'mogong': 'ma công',
  'modao': 'ma đạo',
  'xianqi': 'tiên khí',
  'xianli': 'tiên lực',
  'xianjie': 'tiên giới',
  'xiandao': 'tiên đạo',
  'wuxia': 'võ hiệp',
  'jianghu': 'giang hồ',
  'wulin': 'võ lâm',
  'qinggong': 'khinh công',
  'dianxue': 'điểm huyệt',
  'jianfa': 'kiếm pháp',
  'jianqi': 'kiếm khí',
  'jianyi': 'kiếm ý',
  'jianshu': 'kiếm thuật',
  'jianshi': 'kiếm sĩ',
  'daoshu': 'đao thuật',
  'daofa': 'đao pháp',
  'quanfa': 'quyền pháp',
  'zhangfa': 'chưởng pháp',
  'zhuafa': 'trảo pháp',
  'tuifa': 'thoái pháp',
  'shenfa': 'thân pháp',
  'bufa': 'bộ pháp',
  'gongfu': 'công phu',
  'kungfu': 'công phu',
  'wugong': 'võ công',
  'wushu': 'võ thuật',
  'zhaoshi': 'chiêu thức',
  'jueshi': 'tuyệt thức',
  'miji': 'bí kíp',
  'neijin': 'nội kình',
  'waijin': 'ngoại kình',
  'anqi': 'ám khí',
  'duqi': 'độc khí',
  'zongmen': 'tông môn',
  'menpai': 'môn phái',
  'bangpai': 'bang phái',
  'jiazu': 'gia tộc',
  'shijia': 'thế gia',
  'huangshi': 'hoàng thất',
  'wangfu': 'vương phủ',
  'gongdian': 'cung điện',
  'dongtian': 'động thiên',
  'fudi': 'phúc địa',
  'mojie': 'ma giới',
  'renjie': 'nhân giới',
  'shenjie': 'thần giới',
  'mingfu': 'minh phủ',
  'diyu': 'địa ngục',
  'kunlun': 'côn lôn',
  'wudang': 'võ đang',
  'shaolin': 'thiếu lâm',
  'emei': 'nga mi',
  'huashan': 'hoa sơn',
  'shifu': 'sư phụ',
  'shizun': 'sư tôn',
  'shixiong': 'sư huynh',
  'shidi': 'sư đệ',
  'shimei': 'sư muội',
  'shijie': 'sư tỷ',
  'zhangmen': 'chưởng môn',
  'zhanglao': 'trưởng lão',
  'taishang': 'thái thượng',
  'dizi': 'đệ tử',
  'tudi': 'đồ đệ',
  'daoyou': 'đạo hữu',
  'qianbei': 'tiền bối',
  'wanbei': 'vãn bối',
  'houbei': 'hậu bối',
  'gongzi': 'công tử',
  'xiaojie': 'tiểu thư',
  'nuxia': 'nữ hiệp',
  'daxia': 'đại hiệp',
  'shaoxia': 'thiếu hiệp',
  'laozu': 'lão tổ',
  'zuzhang': 'tộc trưởng',
  'jiazhu': 'gia chủ',
  'mengzhu': 'minh chủ',
  'jiaozhu': 'giáo chủ',
  'bangzhu': 'bang chủ',
  'tangzhu': 'đường chủ',
  'guzhu': 'cốc chủ',
  'daozhu': 'đảo chủ',
  'chengzhu': 'thành chủ',
  'huangdi': 'hoàng đế',
  'wangye': 'vương gia',
  'taizi': 'thái tử',
  'huanghou': 'hoàng hậu',
  'guifei': 'quý phi',
  'fujun': 'phu quân',
  'furen': 'phu nhân',
  'niangniang': 'nương nương',
  'fabao': 'pháp bảo',
  'shenqi': 'thần khí',
  'xianbao': 'tiên bảo',
  'fulu': 'phù lục',
  'zhenfa': 'trận pháp',
  'feijian': 'phi kiếm',
  'faxiang': 'pháp tướng',
  'danding': 'đan đỉnh',
  'danlu': 'đan lô',
  'danyao': 'đan dược',
  'yaocao': 'dược thảo',
  'lingcao': 'linh thảo',
  'lingshou': 'linh thú',
  'yaoshou': 'yêu thú',
  'moshou': 'ma thú',
  'shenshou': 'thần thú',
  'qilin': 'kỳ lân',
  'fenghuang': 'phượng hoàng',
  'shenlong': 'thần long',
  'xuanwu': 'huyền vũ',
  'baihu': 'bạch hổ',
  'qinglong': 'thanh long',
  'zhuque': 'chu tước',
  'liandan': 'luyện đan',
  'lianwu': 'luyện vũ',
  'lianxin': 'luyện tâm',
  'lianshen': 'luyện thần',
  'xisui': 'tẩy tủy',
  'jiedu': 'giải độc',
  'lunhui': 'luân hồi',
  'zhuanshi': 'chuyển thế',
  'xiongdi': 'huynh đệ',
  'pengyou': 'bằng hữu',
};

export function detectPinyinIssues(
  projectId: string,
  chapterId: string,
  content: string,
  contentHash: string,
): AdaptationScanIssue[] {
  const issues: AdaptationScanIssue[] = [];
  const lowerContent = content.toLowerCase();

  for (const [pinyin, vietnamese] of Object.entries(PINYIN_DICT)) {
    const regex = new RegExp(`\\b${escapeRegex(pinyin)}\\b`, 'gi');
    let match: RegExpExecArray | null;

    while ((match = regex.exec(lowerContent)) !== null) {
      issues.push({
        id: `pinyin-${chapterId}-${match.index}`,
        projectId,
        chapterId,
        trackId: 'translation',
        issueType: 'pinyin_leftover',
        severity: 'critical',
        position: { offset: match.index, length: pinyin.length },
        originalText: content.slice(match.index, match.index + pinyin.length),
        suggestedFix: vietnamese,
        contentHash,
        status: 'open',
        createdAt: new Date().toISOString(),
      });
    }
  }

  return issues;
}

export function suggestVietnamese(pinyinTerm: string): string | null {
  return PINYIN_DICT[pinyinTerm.toLowerCase()] ?? null;
}

function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
