/**
 * File: tag_labels_vi.ts
 * Purpose: Map template tag keys → nhãn tiếng Việt (hiển thị UI)
 * Layer: Lib
 * Domain: StoryTemplate
 */

const TAG_LABEL_VI: Record<string, string> = {
  'alt-history': 'Lịch sử não động',
  ancient: 'Cổ đại',
  'ancient-romance': 'Cổ ngôn',
  angst: 'Ngược tâm',
  'anti-hero': 'Phản anh hùng',
  awakening: 'Thức tỉnh',
  brainwave: 'Não động',
  ceo: 'Tổng tài',
  children: 'Con cái',
  competition: 'Thi đấu',
  contemporary: 'Đương đại',
  'cosmic-horror': 'Kinh dị vũ trụ',
  cthulhu: 'Cthulhu',
  daily: 'Thường ngày',
  dark: 'Tăm tối',
  drama: 'Drama',
  dynasty: 'Vương triều',
  entertainment: 'Giải trí',
  era: 'Niên đại',
  espionage: 'Tình báo',
  esports: 'E-Sports',
  family: 'Gia đình',
  'fantasy-romance': 'Huyễn tưởng ngôn tình',
  'female-lead': 'Nữ chính',
  'flash-fiction': 'Đoản thiên',
  game: 'Game',
  gamelit: 'GameLit',
  gaming: 'Gaming',
  ghost: 'Linh dị',
  grimdark: 'U tối',
  harem: 'Hậu cung',
  historical: 'Lịch sử',
  'historical-romance': 'Cổ trang ngôn tình',
  horror: 'Kinh dị',
  identity: 'Thân phận',
  internet: 'Internet',
  intrigue: 'Mưu kế',
  litrpg: 'LitRPG',
  livestream: 'Livestream',
  lovecraft: 'Lovecraft',
  marriage: 'Hôn nhân',
  melodrama: 'Cẩu huyết',
  military: 'Quân sự',
  modern: 'Hiện đại',
  'modern-romance': 'Ngôn tình hiện đại',
  mystery: 'Bí ẩn',
  nostalgia: 'Hoài niệm',
  palace: 'Cung đình',
  politics: 'Chính trị',
  realistic: 'Hiện thực',
  'republic-era': 'Dân quốc',
  rich: 'Hào môn',
  romance: 'Ngôn tình',
  school: 'Vườn trường',
  'short-story': 'Truyện ngắn',
  'slice-of-life': 'Đời thường',
  sports: 'Thể thao',
  spy: 'Điệp viên',
  substitute: 'Thế thân',
  supernatural: 'Siêu nhiên',
  'supernatural-romance': 'Siêu nhiên ngôn tình',
  superpower: 'Dị năng',
  suspense: 'Hồi hộp',
  sweet: 'Ngọt sủng',
  system: 'Hệ thống',
  'time-travel': 'Xuyên thời gian',
  twist: 'Plot twist',
  urban: 'Đô thị',
  villain: 'Phản diện',
  war: 'Chiến tranh',
  workplace: 'Công sở',
  youth: 'Thanh xuân',
};

export function getTemplateTagLabelVi(tag: string): string {
  const key = tag.toLowerCase().trim();
  return TAG_LABEL_VI[key] ?? tag;
}

