/**
 * File: alt_history_template.ts
 * Purpose: Story template cho thể loại Lịch Sử Xuyên Không / Não Động
 * Layer: Data (Constants)
 * Domain: StoryTemplate
 * Deps: types/story_template
 * Generated by: scripts/convert_templates.ts
 */
import type { StoryTemplate } from '../../types/story_template';

export const ALT_HISTORY_TEMPLATE: StoryTemplate = {
  "id": "alt-history",
  "name": "Lịch Sử Xuyên Không / Não Động",
  "originalName": "历史脑洞",
  "coreSellingPoint": "历史框架 + 设定反转 + 规则博弈。当超自然规则与历史交织，改变历史的代价是什么？",
  "tags": [
    "alt-history",
    "time-travel",
    "historical"
  ],
  "subGenres": [
    {
      "name": "Lịch Sử Xuyên Không / Não Động",
      "description": "历史框架 + 设定反转 + 规则博弈。当超自然规则与历史交织，改变历史的代价是什么？",
      "coreAppeal": "历史框架 + 设定反转 + 规则博弈。当超自然规则与历史交织，改变历史的代价是什么？"
    }
  ],
  "worldRules": [],
  "coolPatterns": [],
  "conflictPatterns": [],
  "outlineArcs": [
    {
      "title": "卷一：入局 (1-60章)",
      "chapterRange": "1-100",
      "coreFocus": "进入历史，发现规则",
      "coreConflict": "边缘人物",
      "climax": "首次利用规则"
    },
    {
      "title": "卷二：立足 (61-150章)",
      "chapterRange": "1-100",
      "coreFocus": "站稳脚跟，积累资源",
      "coreConflict": "有一定影响力",
      "climax": "改变局部历史"
    },
    {
      "title": "卷三：博弈 (151-280章)",
      "chapterRange": "1-100",
      "coreFocus": "与规则/势力博弈",
      "coreConflict": "重要人物",
      "climax": "重大历史事件干预"
    },
    {
      "title": "卷四：抉择 (281-400章)",
      "chapterRange": "1-100",
      "coreFocus": "面临重大抉择",
      "coreConflict": "核心人物",
      "climax": "关键历史节点"
    },
    {
      "title": "卷五：终局 (401-500章)",
      "chapterRange": "1-100",
      "coreFocus": "最终结局",
      "coreConflict": "历史改变者/见证者",
      "climax": "圆满结局"
    }
  ],
  "pitfalls": [
    {
      "description": "Thiết lập trước sau mâu thuẫn.",
      "severity": "critical"
    }
  ],
  "bestPractices": [
    {
      "description": "Thiết lập tự nhất quán."
    }
  ],
  "entityTags": [
    {
      "type": "规则",
      "nameVi": "规则",
      "attributes": [
        "cost",
        "loophole"
      ]
    },
    {
      "type": "历史事件",
      "nameVi": "历史事件",
      "attributes": [
        "changed",
        "impact"
      ]
    },
    {
      "type": "历史人物",
      "nameVi": "历史人物",
      "attributes": [
        "changed",
        "relationship"
      ]
    },
    {
      "type": "因果",
      "nameVi": "因果",
      "attributes": [
        "result",
        "debt"
      ]
    }
  ],
  "constraintPacks": [
    "Pack M08",
    "Pack U02"
  ]
};
