/**
 * File: ancient_romance_template.ts
 * Purpose: Story template cho thể loại Cổ Đại Ngôn Tình
 * Layer: Data (Constants)
 * Domain: StoryTemplate
 * Deps: types/story_template
 * Generated by: scripts/convert_templates.ts
 */
import type { StoryTemplate } from '../../types/story_template';

export const ANCIENT_ROMANCE_TEMPLATE: StoryTemplate = {
  "id": "ancient-romance",
  "name": "Cổ Đại Ngôn Tình",
  "originalName": "古言",
  "coreSellingPoint": "古风韵味 + 权谋争斗 + 情深缘浅。在架空或真实历史背景下，展开爱恨情仇与权力博弈。",
  "tags": [
    "ancient-romance",
    "historical-romance"
  ],
  "subGenres": [
    {
      "name": "Cổ Đại Ngôn Tình",
      "description": "古风韵味 + 权谋争斗 + 情深缘浅。在架空或真实历史背景下，展开爱恨情仇与权力博弈。",
      "coreAppeal": "古风韵味 + 权谋争斗 + 情深缘浅。在架空或真实历史背景下，展开爱恨情仇与权力博弈。"
    }
  ],
  "worldRules": [],
  "coolPatterns": [],
  "conflictPatterns": [],
  "outlineArcs": [
    {
      "title": "卷一：初入深宫/大宅 (1-80章, 20%)",
      "chapterRange": "1-100",
      "coreFocus": "卷一：初入深宫/大宅 (1-80章, 20%)",
      "coreConflict": "",
      "climax": ""
    },
    {
      "title": "卷二：步步为营 (81-180章, 25%)",
      "chapterRange": "1-100",
      "coreFocus": "卷二：步步为营 (81-180章, 25%)",
      "coreConflict": "",
      "climax": "获得阶段性胜利"
    },
    {
      "title": "卷三：风云变幻 (181-300章, 30%)",
      "chapterRange": "1-100",
      "coreFocus": "卷三：风云变幻 (181-300章, 30%)",
      "coreConflict": "",
      "climax": ""
    },
    {
      "title": "卷四：绝地反击 (301-380章, 20%)",
      "chapterRange": "1-100",
      "coreFocus": "卷四：绝地反击 (301-380章, 20%)",
      "coreConflict": "",
      "climax": ""
    },
    {
      "title": "卷五：圆满结局 (381-420章, 15%)",
      "chapterRange": "1-100",
      "coreFocus": "卷五：圆满结局 (381-420章, 15%)",
      "coreConflict": "",
      "climax": ""
    }
  ],
  "pitfalls": [
    {
      "description": "Thiết lập trước sau mâu thuẫn.",
      "severity": "critical"
    }
  ],
  "bestPractices": [
    {
      "description": "Thiết lập tự nhất quán."
    }
  ],
  "entityTags": [
    {
      "type": "位分",
      "nameVi": "位分",
      "attributes": [
        "rank"
      ]
    },
    {
      "type": "势力",
      "nameVi": "势力",
      "attributes": [
        "leader",
        "relation"
      ]
    },
    {
      "type": "计谋",
      "nameVi": "计谋",
      "attributes": [
        "initiator",
        "target"
      ]
    },
    {
      "type": "古词",
      "nameVi": "古词",
      "attributes": [
        "usage"
      ]
    }
  ],
  "languageRegister": {
    "eraLabel": "cổ đại / lịch sử / cung trạch",
    "narrationStyle": "ngôi ba trang nhã, thiên về lễ nghi, ẩn ý và khoảng cách xã hội; tránh lời kể khẩu ngữ hiện đại",
    "hanVietDensity": "dense",
    "hanVietGuidance": "Ưu tiên Hán Việt ở danh xưng, chức vị, địa danh, lễ nghi; không chen từ đời sống hiện đại như một phản xạ tự nhiên.",
    "dictionGuidance": "Nếu cảnh đặt trong Giang Nam, phủ đệ, hậu viện, thâm cung thì danh từ và xưng hô đi kèm cũng phải cùng register cổ phong.",
    "preferredTerms": [
      "kinh thành",
      "phủ",
      "trấn",
      "nội viện",
      "hậu trạch",
      "điện",
      "các"
    ],
    "avoidTerms": [
      "thành phố",
      "căn hộ",
      "cao ốc",
      "app",
      "CEO"
    ],
    "preferredPronouns": [
      "ta",
      "ngươi",
      "thiếp",
      "chàng",
      "thần",
      "bệ hạ",
      "điện hạ",
      "nô tỳ"
    ],
    "forbiddenPronouns": [
      "tôi",
      "anh",
      "em",
      "bạn"
    ],
    "dialogueRules": [
      {
        "context": "giữ khoảng cách, thị uy, hoặc đối đầu",
        "preferredPairs": [
          "ta - ngươi",
          "bổn cung - ngươi"
        ],
        "forbiddenPairs": [
          "tôi - anh",
          "anh - em"
        ],
        "note": "\"Ta - ngươi\" không chỉ dành cho thù địch; còn dùng khi cố ý giữ khoảng cách, ép thế, hoặc hai bên chưa thân."
      },
      {
        "context": "quân thần hoặc chủ-tớ",
        "preferredPairs": [
          "thần - bệ hạ",
          "nô tỳ - nương nương"
        ],
        "forbiddenPairs": [
          "tôi - ông"
        ],
        "note": "Thứ bậc phải hiện rõ ngay trong đại từ."
      },
      {
        "context": "thân mật tình cảm",
        "preferredPairs": [
          "thiếp - chàng",
          "ta - nàng"
        ],
        "forbiddenPairs": [
          "anh - em"
        ],
        "note": "Chỉ dùng khi tình thế và độ thân mật đủ chín."
      }
    ]
  },
  "constraintPacks": [
    "Pack F01",
    "Pack F18",
    "Pack U01"
  ]
};
