/**
 * File: ancient_romance_template.ts
 * Purpose: Story template cho thể loại Cổ Đại Ngôn Tình
 * Layer: Data (Constants)
 * Domain: StoryTemplate
 * Deps: types/story_template
 * Generated by: scripts/convert_templates.ts
 */
import type { StoryTemplate } from '../../types/story_template';

export const ANCIENT_ROMANCE_TEMPLATE: StoryTemplate = {
  "id": "ancient-romance",
  "name": "Cổ Đại Ngôn Tình",
  "originalName": "古言",
  "coreSellingPoint": "古风韵味 + 权谋争斗 + 情深缘浅。在架空或真实历史背景下，展开爱恨情仇与权力博弈。",
  "tags": [
    "ancient-romance",
    "historical-romance"
  ],
  "subGenres": [
    {
      "name": "宫斗流",
      "description": "后宫争宠，步步为营，心机博弈",
      "coreAppeal": "智斗群妃，获得圣宠，步步高升"
    },
    {
      "name": "宅斗流",
      "description": "大家族内斗，婆媳妯娌，管家争权",
      "coreAppeal": "斗倒恶婆婆，掌握管家权，夫妻同心"
    },
    {
      "name": "权谋流",
      "description": "朝堂博弈，家国天下，智计对决",
      "coreAppeal": "运筹帷幄，翻云覆雨，青史留名"
    },
    {
      "name": "甜宠流",
      "description": "甜蜜为主，权谋为辅，糖分爆表",
      "coreAppeal": "男主专宠，众人羡慕，甜蜜日常"
    }
  ],
  "worldRules": [],
  "coolPatterns": [],
  "conflictPatterns": [
    {
      "type": "古言题材模板 (Period Drama / Historical Romance)",
      "source": "> **核心卖点**: 古风韵味 + 权谋争斗 + 情深缘浅。在架空或真实历史背景下，展开爱恨情仇与权力博弈。 --",
      "resolution": "> **核心卖点**: 古风韵味 + 权谋争斗 + 情深缘浅。在架空或真实历史背景下，展开爱恨情仇与权力博弈。 --"
    },
    {
      "type": "宫斗框架",
      "source": "入宫 → 站稳 → 争宠 → 危机 → 登顶/退出 详细阶段： 入宫（选秀/赐婚/家族安排） 初入后宫（被欺负/找靠山） 获得圣宠（才艺/性格/机缘） 树敌（皇后/宠妃的打压） 步步高升（晋位/生子） 重大危机（被陷害/失宠） 绝地反击（揭露真相/翻盘） 最终结局（登后位/离宫/帝后和谐）",
      "resolution": "入宫 → 站稳 → 争宠 → 危机 → 登顶/退出 详细阶段： 入宫（选秀/赐婚/家族安排） 初入后宫（被欺负/找靠山） 获得圣宠（才艺/性格/机缘） 树敌（皇后/宠妃的打压） 步步高升（晋位/生子） 重大危机（被陷害/失宠） 绝地反击（揭露真相/翻盘） 最终结局（登后位/离宫/帝后和谐）"
    },
    {
      "type": "宅斗框架",
      "source": "嫁入 → 立足 → 掌家 → 危机 → 当家 详细阶段： 嫁入（高嫁/低嫁/冲喜） 婆媳过招（立规矩/被刁难） 妯娌争斗（争资源/争宠） 丈夫关系（冷淡/渐热/误会） 管家权争夺 家族危机（抄家/落魄） 力挽狂澜 成为当家主母",
      "resolution": "嫁入 → 立足 → 掌家 → 危机 → 当家 详细阶段： 嫁入（高嫁/低嫁/冲喜） 婆媳过招（立规矩/被刁难） 妯娌争斗（争资源/争宠） 丈夫关系（冷淡/渐热/误会） 管家权争夺 家族危机（抄家/落魄） 力挽狂澜 成为当家主母"
    },
    {
      "type": "权谋框架",
      "source": "卷入 → 站队 → 博弈 → 决战 → 新局 详细阶段： 被卷入政治漩涡 选择阵营/被迫站队 参与谋划 多方博弈 关键情报/转折 最终决战 新的格局 --",
      "resolution": "卷入 → 站队 → 博弈 → 决战 → 新局 详细阶段： 被卷入政治漩涡 选择阵营/被迫站队 参与谋划 多方博弈 关键情报/转折 最终决战 新的格局 --"
    },
    {
      "type": "卷一：初入深宫/大宅 (1-80章, 20%)",
      "source": "**开篇**: 入宫/出嫁的契机 **人物登场**: 主要势力、关键配角 **核心任务**: 站稳脚跟，熟悉环境 **小高潮**: 第一次危机化解",
      "resolution": "**开篇**: 入宫/出嫁的契机 **人物登场**: 主要势力、关键配角 **核心任务**: 站稳脚跟，熟悉环境 **小高潮**: 第一次危机化解"
    },
    {
      "type": "卷二：步步为营 (81-180章, 25%)",
      "source": "与主要对手的第一轮交锋",
      "resolution": "与主要对手的第一轮交锋"
    },
    {
      "type": "卷三：风云变幻 (181-300章, 30%)",
      "source": "**格局扩大**: 更高层次的博弈 **危机加深**: 被陷害/失宠/家族牵连 **黑暗时刻**: 跌入谷底 **转折**: 关键助力出现",
      "resolution": "**格局扩大**: 更高层次的博弈 **危机加深**: 被陷害/失宠/家族牵连 **黑暗时刻**: 跌入谷底 **转折**: 关键助力出现"
    },
    {
      "type": "争宠桥段",
      "source": "才艺惊艳: 一曲/一舞/一诗技惊四座 智解困局: 危机时刻展现智慧 救驾有功: 关键时刻救了贵人 以退为进: 示弱博取同情 借力打力: 利用对手的招数反击",
      "resolution": "才艺惊艳: 一曲/一舞/一诗技惊四座 智解困局: 危机时刻展现智慧 救驾有功: 关键时刻救了贵人 以退为进: 示弱博取同情 借力打力: 利用对手的招数反击"
    }
  ],
  "outlineArcs": [
    {
      "title": "卷一：初入深宫/大宅 (1-80章, 20%)",
      "chapterRange": "1-80",
      "coreFocus": "**开篇**: 入宫/出嫁的契机 **人物登场**: 主要势力、关键配角 **核心任务**: 站稳脚跟，熟悉环境 **小高潮**: 第一次危机化解",
      "coreConflict": "",
      "climax": ""
    },
    {
      "title": "卷二：步步为营 (81-180章, 25%)",
      "chapterRange": "81-180",
      "coreFocus": "**势力布局**: 拉拢盟友，应对敌人 **情感发展**: 与男主关系升温 **核心冲突**: 与主要对手的第一轮交锋 **高潮**: 获得阶段性胜利",
      "coreConflict": "与主要对手的第一轮交锋",
      "climax": "获得阶段性胜利"
    },
    {
      "title": "卷三：风云变幻 (181-300章, 30%)",
      "chapterRange": "181-300",
      "coreFocus": "**格局扩大**: 更高层次的博弈 **危机加深**: 被陷害/失宠/家族牵连 **黑暗时刻**: 跌入谷底 **转折**: 关键助力出现",
      "coreConflict": "",
      "climax": ""
    },
    {
      "title": "卷四：绝地反击 (301-380章, 20%)",
      "chapterRange": "301-380",
      "coreFocus": "**反攻布局**: 收集证据，联合盟友 **真相揭露**: 幕后黑手现形 **最终对决**: 正面交锋 **清算**: 仇人伏法",
      "coreConflict": "",
      "climax": ""
    },
    {
      "title": "卷五：圆满结局 (381-420章, 15%)",
      "chapterRange": "381-420",
      "coreFocus": "**善后处理**: 新格局建立 **情感圆满**: 与男主HE **番外/日常**: 幸福生活 --",
      "coreConflict": "",
      "climax": ""
    }
  ],
  "targetWordCount": "1.000.000 chữ",
  "targetChapterCount": 420,
  "pitfalls": [
    {
      "description": "Thiết lập trước sau mâu thuẫn.",
      "severity": "critical"
    }
  ],
  "bestPractices": [
    {
      "description": "Thiết lập tự nhất quán."
    }
  ],
  "entityTags": [
    {
      "type": "位分",
      "nameVi": "位分",
      "attributes": [
        "rank"
      ]
    },
    {
      "type": "势力",
      "nameVi": "势力",
      "attributes": [
        "leader",
        "relation"
      ]
    },
    {
      "type": "计谋",
      "nameVi": "计谋",
      "attributes": [
        "initiator",
        "target"
      ]
    },
    {
      "type": "古词",
      "nameVi": "古词",
      "attributes": [
        "usage"
      ]
    }
  ],
  "constraintPacks": [
    "Pack F01",
    "Pack F18",
    "Pack U01"
  ],
  "languageRegister": {
    "eraLabel": "cổ đại / lịch sử / cung trạch",
    "narrationStyle": "ngôi ba trang nhã, thiên về lễ nghi, ẩn ý và khoảng cách xã hội; tránh lời kể khẩu ngữ hiện đại",
    "hanVietDensity": "dense",
    "hanVietGuidance": "Ưu tiên Hán Việt ở danh xưng, chức vị, địa danh, lễ nghi; không chen từ đời sống hiện đại như một phản xạ tự nhiên.",
    "dictionGuidance": "Nếu cảnh đặt trong Giang Nam, phủ đệ, hậu viện, thâm cung thì danh từ và xưng hô đi kèm cũng phải cùng register cổ phong.",
    "preferredTerms": [
      "kinh thành",
      "phủ",
      "trấn",
      "nội viện",
      "hậu trạch",
      "điện",
      "các"
    ],
    "avoidTerms": [
      "thành phố",
      "căn hộ",
      "cao ốc",
      "app",
      "CEO"
    ],
    "preferredPronouns": [
      "ta",
      "ngươi",
      "thiếp",
      "chàng",
      "thần",
      "bệ hạ",
      "điện hạ",
      "nô tỳ"
    ],
    "forbiddenPronouns": [
      "tôi",
      "anh",
      "em",
      "bạn"
    ],
    "dialogueRules": [
      {
        "context": "giữ khoảng cách, thị uy, hoặc đối đầu",
        "preferredPairs": [
          "ta - ngươi",
          "bổn cung - ngươi"
        ],
        "forbiddenPairs": [
          "tôi - anh",
          "anh - em"
        ],
        "note": "\"Ta - ngươi\" không chỉ dành cho thù địch; còn dùng khi cố ý giữ khoảng cách, ép thế, hoặc hai bên chưa thân."
      },
      {
        "context": "quân thần hoặc chủ-tớ",
        "preferredPairs": [
          "thần - bệ hạ",
          "nô tỳ - nương nương"
        ],
        "forbiddenPairs": [
          "tôi - ông"
        ],
        "note": "Thứ bậc phải hiện rõ ngay trong đại từ."
      },
      {
        "context": "thân mật tình cảm",
        "preferredPairs": [
          "thiếp - chàng",
          "ta - nàng"
        ],
        "forbiddenPairs": [
          "anh - em"
        ],
        "note": "Chỉ dùng khi tình thế và độ thân mật đủ chín."
      }
    ]
  }
};
