/**
 * File: brainwave_suspense_template.ts
 * Purpose: Story template cho thể loại Huyền Nghi Não Động
 * Layer: Data (Constants)
 * Domain: StoryTemplate
 * Deps: types/story_template
 * Generated by: scripts/convert_templates.ts
 */
import type { StoryTemplate } from '../../types/story_template';

export const BRAINWAVE_SUSPENSE_TEMPLATE: StoryTemplate = {
  "id": "brainwave-suspense",
  "name": "Huyền Nghi Não Động",
  "originalName": "悬疑脑洞",
  "coreSellingPoint": "逻辑推理 + 规则博弈 + 高智商反转。在规则与推理的交织中，揭开层层迷雾背后的真相。",
  "tags": [
    "suspense",
    "brainwave",
    "twist"
  ],
  "subGenres": [
    {
      "name": "Huyền Nghi Não Động",
      "description": "逻辑推理 + 规则博弈 + 高智商反转。在规则与推理的交织中，揭开层层迷雾背后的真相。",
      "coreAppeal": "逻辑推理 + 规则博弈 + 高智商反转。在规则与推理的交织中，揭开层层迷雾背后的真相。"
    }
  ],
  "worldRules": [],
  "coolPatterns": [],
  "conflictPatterns": [],
  "outlineArcs": [
    {
      "title": "卷一：入局 (1-50章)",
      "chapterRange": "1-100",
      "coreFocus": "进入悬疑世界，了解规则",
      "coreConflict": "",
      "climax": "首次破解谜题"
    },
    {
      "title": "卷二：成长 (51-120章)",
      "chapterRange": "1-100",
      "coreFocus": "推理能力提升",
      "coreConflict": "",
      "climax": "解决重大案件"
    },
    {
      "title": "卷三：深入 (121-200章)",
      "chapterRange": "1-100",
      "coreFocus": "接触核心谜题",
      "coreConflict": "",
      "climax": "发现关键线索"
    },
    {
      "title": "卷四：对决 (201-280章)",
      "chapterRange": "1-100",
      "coreFocus": "与幕后黑手对决",
      "coreConflict": "",
      "climax": "揭露幕后黑手"
    },
    {
      "title": "卷五：终局 (281-350章)",
      "chapterRange": "1-100",
      "coreFocus": "最终真相，终极对决",
      "coreConflict": "",
      "climax": "圆满结局"
    }
  ],
  "pitfalls": [
    {
      "description": "Thiết lập trước sau mâu thuẫn.",
      "severity": "critical"
    }
  ],
  "bestPractices": [
    {
      "description": "Thiết lập tự nhất quán."
    }
  ],
  "entityTags": [
    {
      "type": "线索",
      "nameVi": "线索",
      "attributes": [
        "location",
        "pointer",
        "revealed"
      ]
    },
    {
      "type": "规则",
      "nameVi": "规则",
      "attributes": [
        "loophole",
        "penalty"
      ]
    },
    {
      "type": "谜题",
      "nameVi": "谜题",
      "attributes": [
        "answer",
        "clues"
      ]
    },
    {
      "type": "反转",
      "nameVi": "反转",
      "attributes": [
        "foreshadow",
        "chapter"
      ]
    }
  ],
  "constraintPacks": [
    "Pack M06",
    "Pack M07",
    "Pack U02"
  ]
};
