/**
 * File: ceo_romance_template.ts
 * Purpose: Story template cho thể loại Hào Môn Tổng Tài
 * Layer: Data (Constants)
 * Domain: StoryTemplate
 * Deps: types/story_template
 * Generated by: scripts/convert_templates.ts
 */
import type { StoryTemplate } from '../../types/story_template';

export const CEO_ROMANCE_TEMPLATE: StoryTemplate = {
  "id": "ceo-romance",
  "name": "Hào Môn Tổng Tài",
  "originalName": "豪门总裁",
  "coreSellingPoint": "权力差距 + 契约关系 + 情感拉扯。灰姑娘与王子的现代演绎，在金钱与真心之间抉择。",
  "tags": [
    "ceo",
    "rich",
    "romance",
    "modern"
  ],
  "subGenres": [
    {
      "name": "Hào Môn Tổng Tài",
      "description": "权力差距 + 契约关系 + 情感拉扯。灰姑娘与王子的现代演绎，在金钱与真心之间抉择。",
      "coreAppeal": "权力差距 + 契约关系 + 情感拉扯。灰姑娘与王子的现代演绎，在金钱与真心之间抉择。"
    }
  ],
  "worldRules": [],
  "coolPatterns": [],
  "conflictPatterns": [],
  "outlineArcs": [
    {
      "title": "卷一：相遇 (1-50章)",
      "chapterRange": "1-100",
      "coreFocus": "男女主相遇，建立契约关系",
      "coreConflict": "",
      "climax": "签订契约，开始同居"
    },
    {
      "title": "卷二：暧昧 (51-120章)",
      "chapterRange": "1-100",
      "coreFocus": "日常相处，感情萌芽",
      "coreConflict": "",
      "climax": "第一次心动/吃醋"
    },
    {
      "title": "卷三：考验 (121-200章)",
      "chapterRange": "1-100",
      "coreFocus": "感情遇到考验",
      "coreConflict": "",
      "climax": "误会/分离"
    },
    {
      "title": "卷四：确认 (201-280章)",
      "chapterRange": "1-100",
      "coreFocus": "解除误会，确认感情",
      "coreConflict": "",
      "climax": "正式在一起"
    },
    {
      "title": "卷五：圆满 (281-350章)",
      "chapterRange": "1-100",
      "coreFocus": "获得认可，修成正果",
      "coreConflict": "",
      "climax": "盛大婚礼"
    }
  ],
  "pitfalls": [
    {
      "description": "Thiết lập trước sau mâu thuẫn.",
      "severity": "critical"
    }
  ],
  "bestPractices": [
    {
      "description": "Thiết lập tự nhất quán."
    }
  ],
  "entityTags": [
    {
      "type": "家族",
      "nameVi": "家族",
      "attributes": [
        "assets",
        "power"
      ]
    },
    {
      "type": "契约",
      "nameVi": "契约",
      "attributes": [
        "duration",
        "penalty"
      ]
    },
    {
      "type": "关系",
      "nameVi": "关系",
      "attributes": [
        "stage",
        "obstacle"
      ]
    },
    {
      "type": "秘密",
      "nameVi": "秘密",
      "attributes": [
        "impact",
        "reveal"
      ]
    }
  ],
  "constraintPacks": [
    "Pack F07",
    "Pack U01"
  ]
};
