/**
 * File: cthulhu_template.ts
 * Purpose: Story template cho thể loại Cthulhu / Vũ Trụ Kinh Hoàng
 * Layer: Data (Constants)
 * Domain: StoryTemplate
 * Deps: types/story_template
 * Generated by: scripts/convert_templates.ts
 */
import type { StoryTemplate } from '../../types/story_template';

export const CTHULHU_TEMPLATE: StoryTemplate = {
  "id": "cthulhu",
  "name": "Cthulhu / Vũ Trụ Kinh Hoàng",
  "originalName": "克苏鲁",
  "coreSellingPoint": "不可名状 + 理性崩塌 + 真相代价。读者快感来自“接近真相但无法承受真相”。",
  "tags": [
    "cthulhu",
    "cosmic-horror",
    "lovecraft"
  ],
  "subGenres": [
    {
      "name": "Cthulhu / Vũ Trụ Kinh Hoàng",
      "description": "不可名状 + 理性崩塌 + 真相代价。读者快感来自“接近真相但无法承受真相”。",
      "coreAppeal": "不可名状 + 理性崩塌 + 真相代价。读者快感来自“接近真相但无法承受真相”。"
    }
  ],
  "worldRules": [],
  "coolPatterns": [],
  "conflictPatterns": [],
  "outlineArcs": [
    {
      "title": "卷一：异响 (1-70章)",
      "chapterRange": "1-100",
      "coreFocus": "发现异常与第一条规则",
      "coreConflict": "",
      "climax": "首次活着离开污染区"
    },
    {
      "title": "卷二：深潜 (71-180章)",
      "chapterRange": "1-100",
      "coreFocus": "调查网络展开，组织与教团对抗",
      "coreConflict": "",
      "climax": "关键人物污染失控"
    },
    {
      "title": "卷三：裂隙 (181-320章)",
      "chapterRange": "1-100",
      "coreFocus": "世界局部规则改写",
      "coreConflict": "",
      "climax": "代价型胜利，保住核心城市"
    },
    {
      "title": "卷四：归零 (321-500章)",
      "chapterRange": "1-100",
      "coreFocus": "主角直面深层真相",
      "coreConflict": "",
      "climax": "牺牲与封印，重构新秩序"
    }
  ],
  "pitfalls": [
    {
      "description": "Thiết lập trước sau mâu thuẫn.",
      "severity": "critical"
    }
  ],
  "bestPractices": [
    {
      "description": "Thiết lập tự nhất quán."
    }
  ],
  "entityTags": [
    {
      "type": "污染源",
      "nameVi": "污染源",
      "attributes": [
        "rule",
        "radius"
      ]
    },
    {
      "type": "教团",
      "nameVi": "教团",
      "attributes": [
        "ritual",
        "weakness"
      ]
    },
    {
      "type": "禁忌物",
      "nameVi": "禁忌物",
      "attributes": [
        "cost",
        "trigger"
      ]
    },
    {
      "type": "调查者",
      "nameVi": "调查者",
      "attributes": [
        "sanity",
        "clue"
      ]
    }
  ],
  "constraintPacks": [
    "Pack M21",
    "Pack U04"
  ]
};
