/**
 * File: dark_theme_template.ts
 * Purpose: Story template cho thể loại Hắc Ám Đề Tài / Anti-Hero
 * Layer: Data (Constants)
 * Domain: StoryTemplate
 * Deps: types/story_template
 * Generated by: scripts/convert_templates.ts
 */
import type { StoryTemplate } from '../../types/story_template';

export const DARK_THEME_TEMPLATE: StoryTemplate = {
  "id": "dark-theme",
  "name": "Hắc Ám Đề Tài / Anti-Hero",
  "originalName": "黑暗题材",
  "coreSellingPoint": "Thể loại đặc sắc.",
  "tags": [
    "dark",
    "anti-hero",
    "villain",
    "grimdark"
  ],
  "subGenres": [
    {
      "name": "Hắc Ám Đề Tài / Anti-Hero",
      "description": "Thể loại đặc sắc.",
      "coreAppeal": "Thể loại đặc sắc."
    }
  ],
  "worldRules": [
    {
      "name": "世界类型选择",
      "description": "类型 / 特点 / 适合风格 ------ / ------ / ---------- 末日废土 / 文明崩塌、资源匮乏 / 生存竞争 崩坏修真 / 修真世界黑暗面 / 弱肉强食 黑暗都市 / 现代社会阴暗面 / 隐秘渗透 星际黑暗 / 宇宙尺度征服 / 种族战争"
    },
    {
      "name": "生存法则",
      "description": "弱肉强食 → 适者生存 → 强者为王 → 胜者通吃"
    },
    {
      "name": "势力格局",
      "description": "势力 / 定位 / 功能 ------ / ------ / ------ 主角势力 / 崛起中的黑暗帝国 / 核心发展线 抵抗势力 / 人类最后希望 / 制造冲突 第三方势力 / 中立/投机 / 增加变数 敌对势力 / 竞争者/旧秩序 / 主要对手 --"
    }
  ],
  "coolPatterns": [
    {
      "name": "爽点类型",
      "scenario": "类型 / 触发 / 效果 ------ / ------ / ------ 支配爽 / 绝对控制他人 / 权力满足 征服爽 / 攻城略地 / 扩张快感 吞噬爽 / 掠夺能力/资源 / 成长满足 碾压爽 / 实力差距展示 / 强者快感 恐惧爽 / 让敌人恐惧 / 威慑满足",
      "appeal": "类型 / 触发 / 效果 ------ / ------ / ------ 支配爽 / 绝对控制他人 / 权力满足 征服爽 / 攻城略地 / 扩张快感 吞噬爽 / 掠夺能力/资源 / 成长满足 碾压爽 / 实力差距展示 / 强者快感 恐惧爽 / 让敌人恐惧 / 威慑满足"
    },
    {
      "name": "爽点结构",
      "scenario": "展示实力差距 → 敌人恐惧/绝望 → 碾压/征服 → 收获战利品",
      "appeal": "展示实力差距 → 敌人恐惧/绝望 → 碾压/征服 → 收获战利品"
    },
    {
      "name": "黑暗仪式感",
      "scenario": "登基/加冕场景 敌人臣服场景 势力扩张场景 进化突破场景 --",
      "appeal": "登基/加冕场景 敌人臣服场景 势力扩张场景 进化突破场景 --"
    }
  ],
  "conflictPatterns": [
    {
      "type": "末日废土",
      "source": "文明崩塌、资源匮乏",
      "resolution": "生存竞争"
    },
    {
      "type": "崩坏修真",
      "source": "修真世界黑暗面",
      "resolution": "弱肉强食"
    },
    {
      "type": "黑暗都市",
      "source": "现代社会阴暗面",
      "resolution": "隐秘渗透"
    },
    {
      "type": "星际黑暗",
      "source": "宇宙尺度征服",
      "resolution": "种族战争"
    },
    {
      "type": "主角势力",
      "source": "崛起中的黑暗帝国",
      "resolution": "崛起中的黑暗帝国"
    },
    {
      "type": "抵抗势力",
      "source": "人类最后希望",
      "resolution": "人类最后希望"
    },
    {
      "type": "第三方势力",
      "source": "中立/投机",
      "resolution": "中立/投机"
    },
    {
      "type": "敌对势力",
      "source": "竞争者/旧秩序",
      "resolution": "竞争者/旧秩序"
    },
    {
      "type": "身体恐怖",
      "source": "变异、畸形",
      "resolution": "变异、畸形"
    },
    {
      "type": "心理恐怖",
      "source": "精神控制、洗脑",
      "resolution": "精神控制、洗脑"
    },
    {
      "type": "存在恐怖",
      "source": "无法理解的存在",
      "resolution": "无法理解的存在"
    },
    {
      "type": "绝望恐怖",
      "source": "无法逃脱的命运",
      "resolution": "无法逃脱的命运"
    },
    {
      "type": "氛围描写",
      "source": "环境压迫：阴暗、腐朽、死寂 感官刺激：腥臭、黏腻、刺耳 心理暗示：被注视、无处可逃",
      "resolution": "环境压迫：阴暗、腐朽、死寂 感官刺激：腥臭、黏腻、刺耳 心理暗示：被注视、无处可逃"
    },
    {
      "type": "发展期（10-100章）",
      "source": "势力扩张 能力进化 征服/吞噬更强对手 建立新秩序",
      "resolution": "势力扩张 能力进化 征服/吞噬更强对手 建立新秩序"
    }
  ],
  "outlineArcs": [
    {
      "title": "Quyển 1: Khởi Đầu",
      "chapterRange": "1-80",
      "coreFocus": "Giới thiệu thế giới.",
      "coreConflict": "Xung đột đầu tiên.",
      "climax": "Bước ngoặt."
    },
    {
      "title": "Quyển 2: Phát Triển",
      "chapterRange": "81-200",
      "coreFocus": "Mở rộng.",
      "coreConflict": "Xung đột chính.",
      "climax": "Đỉnh cao."
    },
    {
      "title": "Quyển 3: Kết Thúc",
      "chapterRange": "201-350",
      "coreFocus": "Giải quyết.",
      "coreConflict": "Đối đầu cuối.",
      "climax": "Viên mãn."
    }
  ],
  "pitfalls": [
    {
      "description": "Thiết lập trước sau mâu thuẫn.",
      "severity": "critical"
    }
  ],
  "bestPractices": [
    {
      "description": "Thiết lập tự nhất quán."
    }
  ],
  "entityTags": [
    {
      "type": "nhan_vat",
      "nameVi": "Nhân vật",
      "attributes": [
        "tính cách",
        "vai trò"
      ]
    }
  ],
  "constraintPacks": [
    "Pack M16",
    "Pack U01"
  ]
};
