/**
 * File: dark_theme_template.ts
 * Purpose: Story template cho thể loại Hắc Ám Đề Tài / Anti-Hero
 * Layer: Data (Constants)
 * Domain: StoryTemplate
 * Deps: types/story_template
 * Generated by: scripts/convert_templates.ts
 */
import type { StoryTemplate } from '../../types/story_template';

export const DARK_THEME_TEMPLATE: StoryTemplate = {
  "id": "dark-theme",
  "name": "Hắc Ám Đề Tài / Anti-Hero",
  "originalName": "黑暗题材",
  "coreSellingPoint": "Thể loại đặc sắc.",
  "tags": [
    "dark",
    "anti-hero",
    "villain",
    "grimdark"
  ],
  "subGenres": [
    {
      "name": "Hắc Ám Đề Tài / Anti-Hero",
      "description": "Thể loại đặc sắc.",
      "coreAppeal": "Thể loại đặc sắc."
    }
  ],
  "worldRules": [],
  "coolPatterns": [],
  "conflictPatterns": [],
  "outlineArcs": [
    {
      "title": "Quyển 1: Khởi Đầu",
      "chapterRange": "1-80",
      "coreFocus": "Giới thiệu thế giới.",
      "coreConflict": "Xung đột đầu tiên.",
      "climax": "Bước ngoặt."
    },
    {
      "title": "Quyển 2: Phát Triển",
      "chapterRange": "81-200",
      "coreFocus": "Mở rộng.",
      "coreConflict": "Xung đột chính.",
      "climax": "Đỉnh cao."
    },
    {
      "title": "Quyển 3: Kết Thúc",
      "chapterRange": "201-350",
      "coreFocus": "Giải quyết.",
      "coreConflict": "Đối đầu cuối.",
      "climax": "Viên mãn."
    }
  ],
  "pitfalls": [
    {
      "description": "Thiết lập trước sau mâu thuẫn.",
      "severity": "critical"
    }
  ],
  "bestPractices": [
    {
      "description": "Thiết lập tự nhất quán."
    }
  ],
  "entityTags": [
    {
      "type": "nhan_vat",
      "nameVi": "Nhân vật",
      "attributes": [
        "tính cách",
        "vai trò"
      ]
    }
  ],
  "constraintPacks": [
    "Pack M16",
    "Pack U01"
  ]
};
