/**
 * File: era_story_template.ts
 * Purpose: Story template cho thể loại Niên Đại / Thời Kỳ Đặc Biệt
 * Layer: Data (Constants)
 * Domain: StoryTemplate
 * Deps: types/story_template
 * Generated by: scripts/convert_templates.ts
 */
import type { StoryTemplate } from '../../types/story_template';

export const ERA_STORY_TEMPLATE: StoryTemplate = {
  "id": "era-story",
  "name": "Niên Đại / Thời Kỳ Đặc Biệt",
  "originalName": "年代",
  "coreSellingPoint": "时代背景 + 生活奋斗 + 情感共鸣。在特定年代的洪流中，书写小人物的奋斗史诗。",
  "tags": [
    "era",
    "nostalgia",
    "slice-of-life"
  ],
  "subGenres": [
    {
      "name": "Niên Đại / Thời Kỳ Đặc Biệt",
      "description": "时代背景 + 生活奋斗 + 情感共鸣。在特定年代的洪流中，书写小人物的奋斗史诗。",
      "coreAppeal": "时代背景 + 生活奋斗 + 情感共鸣。在特定年代的洪流中，书写小人物的奋斗史诗。"
    }
  ],
  "worldRules": [],
  "coolPatterns": [],
  "conflictPatterns": [],
  "outlineArcs": [
    {
      "title": "卷一：立足 (1-60章)",
      "chapterRange": "1-100",
      "coreFocus": "穿越/重生，适应环境",
      "coreConflict": "底层",
      "climax": "站稳脚跟，改善生活"
    },
    {
      "title": "卷二：发展 (61-150章)",
      "chapterRange": "1-100",
      "coreFocus": "抓住机遇，开始积累",
      "coreConflict": "中下层",
      "climax": "获得第一桶金"
    },
    {
      "title": "卷三：崛起 (151-250章)",
      "chapterRange": "1-100",
      "coreFocus": "事业发展，地位提升",
      "coreConflict": "中层",
      "climax": "成为当地富户"
    },
    {
      "title": "卷四：巅峰 (251-350章)",
      "chapterRange": "1-100",
      "coreFocus": "事业巅峰，家庭圆满",
      "coreConflict": "上层",
      "climax": "达到人生巅峰"
    },
    {
      "title": "卷五：圆满 (351-400章)",
      "chapterRange": "1-100",
      "coreFocus": "子孙满堂，安享晚年",
      "coreConflict": "顶层",
      "climax": "圆满结局"
    }
  ],
  "pitfalls": [
    {
      "description": "Thiết lập trước sau mâu thuẫn.",
      "severity": "critical"
    }
  ],
  "bestPractices": [
    {
      "description": "Thiết lập tự nhất quán."
    }
  ],
  "entityTags": [
    {
      "type": "时代事件",
      "nameVi": "时代事件",
      "attributes": [
        "year",
        "impact"
      ]
    },
    {
      "type": "资源",
      "nameVi": "资源",
      "attributes": [
        "rarity",
        "source"
      ]
    },
    {
      "type": "关系",
      "nameVi": "关系",
      "attributes": [
        "status"
      ]
    },
    {
      "type": "产业",
      "nameVi": "产业",
      "attributes": [
        "scale",
        "profit"
      ]
    }
  ],
  "constraintPacks": [
    "Pack F12",
    "Pack U02"
  ]
};
