/**
 * File: esports_template.ts
 * Purpose: Story template cho thể loại Điện Cạnh / E-Sports
 * Layer: Data (Constants)
 * Domain: StoryTemplate
 * Deps: types/story_template
 * Generated by: scripts/convert_templates.ts
 */
import type { StoryTemplate } from '../../types/story_template';

export const ESPORTS_TEMPLATE: StoryTemplate = {
  "id": "esports",
  "name": "Điện Cạnh / E-Sports",
  "originalName": "电竞",
  "coreSellingPoint": "逆风翻盘 + 赛场高压 + 团队成长。以“比赛结果”驱动强节奏与持续追更。",
  "tags": [
    "esports",
    "gaming",
    "competition"
  ],
  "subGenres": [
    {
      "name": "Điện Cạnh / E-Sports",
      "description": "逆风翻盘 + 赛场高压 + 团队成长。以“比赛结果”驱动强节奏与持续追更。",
      "coreAppeal": "逆风翻盘 + 赛场高压 + 团队成长。以“比赛结果”驱动强节奏与持续追更。"
    }
  ],
  "worldRules": [],
  "coolPatterns": [],
  "conflictPatterns": [],
  "outlineArcs": [
    {
      "title": "卷一：入局 (1-80章)",
      "chapterRange": "1-100",
      "coreFocus": "进入职业体系，建立首个团队目标",
      "coreConflict": "",
      "climax": "首次关键胜局"
    },
    {
      "title": "卷二：磨合 (81-180章)",
      "chapterRange": "1-100",
      "coreFocus": "队内矛盾与战术磨合",
      "coreConflict": "",
      "climax": "让二追三名场面"
    },
    {
      "title": "卷三：破圈 (181-320章)",
      "chapterRange": "1-100",
      "coreFocus": "进入顶级联赛，舆论压力上升",
      "coreConflict": "",
      "climax": "宿敌战翻盘"
    },
    {
      "title": "卷四：登顶 (321-520章)",
      "chapterRange": "1-100",
      "coreFocus": "季后赛与国际赛双线作战",
      "coreConflict": "",
      "climax": "决胜局夺冠"
    },
    {
      "title": "卷五：新王朝 (521-700章)",
      "chapterRange": "1-100",
      "coreFocus": "守冠、重建、培养新人",
      "coreConflict": "",
      "climax": "传承与闭环"
    }
  ],
  "pitfalls": [
    {
      "description": "Thiết lập trước sau mâu thuẫn.",
      "severity": "critical"
    }
  ],
  "bestPractices": [
    {
      "description": "Thiết lập tự nhất quán."
    }
  ],
  "entityTags": [
    {
      "type": "战队",
      "nameVi": "战队",
      "attributes": [
        "coach",
        "captain"
      ]
    },
    {
      "type": "选手",
      "nameVi": "选手",
      "attributes": [
        "role",
        "style"
      ]
    },
    {
      "type": "赛事",
      "nameVi": "赛事",
      "attributes": [
        "stage",
        "stakes"
      ]
    },
    {
      "type": "战术",
      "nameVi": "战术",
      "attributes": [
        "counter",
        "risk"
      ]
    }
  ],
  "constraintPacks": [
    "Pack M12",
    "Pack U01"
  ]
};
