/**
 * File: fantasy_romance_template.ts
 * Purpose: Story template cho thể loại Huyễn Tưởng Ngôn Tình
 * Layer: Data (Constants)
 * Domain: StoryTemplate
 * Deps: types/story_template
 * Generated by: scripts/convert_templates.ts
 */
import type { StoryTemplate } from '../../types/story_template';

export const FANTASY_ROMANCE_TEMPLATE: StoryTemplate = {
  "id": "fantasy-romance",
  "name": "Huyễn Tưởng Ngôn Tình",
  "originalName": "幻想言情",
  "coreSellingPoint": "异世界规则 + 情感牺牲 + 宿命反转。在奇幻的世界里，书写跨越种族与命运的爱情。",
  "tags": [
    "fantasy-romance",
    "supernatural-romance"
  ],
  "subGenres": [
    {
      "name": "Huyễn Tưởng Ngôn Tình",
      "description": "异世界规则 + 情感牺牲 + 宿命反转。在奇幻的世界里，书写跨越种族与命运的爱情。",
      "coreAppeal": "异世界规则 + 情感牺牲 + 宿命反转。在奇幻的世界里，书写跨越种族与命运的爱情。"
    }
  ],
  "worldRules": [],
  "coolPatterns": [],
  "conflictPatterns": [],
  "outlineArcs": [
    {
      "title": "卷一：相遇 (1-60章)",
      "chapterRange": "1-100",
      "coreFocus": "命定相遇，情感萌芽",
      "coreConflict": "",
      "climax": "第一次心动"
    },
    {
      "title": "卷二：相知 (61-150章)",
      "chapterRange": "1-100",
      "coreFocus": "深入了解，感情升温",
      "coreConflict": "",
      "climax": "确认心意"
    },
    {
      "title": "卷三：考验 (151-250章)",
      "chapterRange": "1-100",
      "coreFocus": "禁忌/阻碍出现",
      "coreConflict": "",
      "climax": "被迫分开"
    },
    {
      "title": "卷四：守护 (251-350章)",
      "chapterRange": "1-100",
      "coreFocus": "为爱对抗一切",
      "coreConflict": "",
      "climax": "打破禁忌"
    },
    {
      "title": "卷五：圆满 (351-400章)",
      "chapterRange": "1-100",
      "coreFocus": "有情人终成眷属",
      "coreConflict": "",
      "climax": "圆满结局"
    }
  ],
  "pitfalls": [
    {
      "description": "Thiết lập trước sau mâu thuẫn.",
      "severity": "critical"
    }
  ],
  "bestPractices": [
    {
      "description": "Thiết lập tự nhất quán."
    }
  ],
  "entityTags": [
    {
      "type": "种族",
      "nameVi": "种族",
      "attributes": [
        "lifespan",
        "power"
      ]
    },
    {
      "type": "禁忌",
      "nameVi": "禁忌",
      "attributes": [
        "penalty",
        "loophole"
      ]
    },
    {
      "type": "羁绊",
      "nameVi": "羁绊",
      "attributes": [
        "origin",
        "break"
      ]
    },
    {
      "type": "神器",
      "nameVi": "神器",
      "attributes": [
        "owner",
        "significance"
      ]
    }
  ],
  "constraintPacks": [
    "Pack F11",
    "Pack U01"
  ]
};
