/**
 * File: female_suspense_template.ts
 * Purpose: Story template cho thể loại Nữ Tần Huyền Nghi
 * Layer: Data (Constants)
 * Domain: StoryTemplate
 * Deps: types/story_template
 * Generated by: scripts/convert_templates.ts
 */
import type { StoryTemplate } from '../../types/story_template';

export const FEMALE_SUSPENSE_TEMPLATE: StoryTemplate = {
  "id": "female-suspense",
  "name": "Nữ Tần Huyền Nghi",
  "originalName": "女频悬疑",
  "coreSellingPoint": "逻辑推理 + 人性情感 + 关系反转。在亲密关系的迷雾中，用细腻的观察揭开真相。",
  "tags": [
    "female-lead",
    "suspense",
    "mystery"
  ],
  "subGenres": [
    {
      "name": "Nữ Tần Huyền Nghi",
      "description": "逻辑推理 + 人性情感 + 关系反转。在亲密关系的迷雾中，用细腻的观察揭开真相。",
      "coreAppeal": "逻辑推理 + 人性情感 + 关系反转。在亲密关系的迷雾中，用细腻的观察揭开真相。"
    }
  ],
  "worldRules": [],
  "coolPatterns": [],
  "conflictPatterns": [],
  "outlineArcs": [
    {
      "title": "卷一：疑云 (1-50章)",
      "chapterRange": "1-100",
      "coreFocus": "发现异常，产生怀疑",
      "coreConflict": "",
      "climax": "第一个重大发现"
    },
    {
      "title": "卷二：追查 (51-120章)",
      "chapterRange": "1-100",
      "coreFocus": "收集线索，接近真相",
      "coreConflict": "",
      "climax": "发现关键证据"
    },
    {
      "title": "卷三：危机 (121-200章)",
      "chapterRange": "1-100",
      "coreFocus": "真相即将揭露，危机四伏",
      "coreConflict": "",
      "climax": "身份/关系反转"
    },
    {
      "title": "卷四：真相 (201-280章)",
      "chapterRange": "1-100",
      "coreFocus": "真相大白，正义伸张",
      "coreConflict": "",
      "climax": "最终对决"
    },
    {
      "title": "卷五：新生 (281-350章)",
      "chapterRange": "1-100",
      "coreFocus": "走出阴影，开始新生活",
      "coreConflict": "",
      "climax": "圆满结局"
    }
  ],
  "pitfalls": [
    {
      "description": "Thiết lập trước sau mâu thuẫn.",
      "severity": "critical"
    }
  ],
  "bestPractices": [
    {
      "description": "Thiết lập tự nhất quán."
    }
  ],
  "entityTags": [
    {
      "type": "线索",
      "nameVi": "线索",
      "attributes": [
        "location",
        "pointer"
      ]
    },
    {
      "type": "关系",
      "nameVi": "关系",
      "attributes": [
        "truth",
        "secret"
      ]
    },
    {
      "type": "秘密",
      "nameVi": "秘密",
      "attributes": [
        "impact",
        "reveal"
      ]
    },
    {
      "type": "反转",
      "nameVi": "反转",
      "attributes": [
        "foreshadow",
        "chapter"
      ]
    }
  ],
  "constraintPacks": [
    "Pack F13",
    "Pack U02"
  ]
};
