/**
 * File: game_sports_template.ts
 * Purpose: Story template cho thể loại Game / Thể Thao
 * Layer: Data (Constants)
 * Domain: StoryTemplate
 * Deps: types/story_template
 * Generated by: scripts/convert_templates.ts
 */
import type { StoryTemplate } from '../../types/story_template';

export const GAME_SPORTS_TEMPLATE: StoryTemplate = {
  "id": "game-sports",
  "name": "Game / Thể Thao",
  "originalName": "游戏体育",
  "coreSellingPoint": "竞技对抗 + 规则博弈 + 团队成长。在赛场上燃烧青春，用实力证明一切。",
  "tags": [
    "game",
    "sports",
    "esports",
    "competition"
  ],
  "subGenres": [
    {
      "name": "Game / Thể Thao",
      "description": "竞技对抗 + 规则博弈 + 团队成长。在赛场上燃烧青春，用实力证明一切。",
      "coreAppeal": "竞技对抗 + 规则博弈 + 团队成长。在赛场上燃烧青春，用实力证明一切。"
    }
  ],
  "worldRules": [],
  "coolPatterns": [],
  "conflictPatterns": [],
  "outlineArcs": [
    {
      "title": "卷一：入门 (1-60章)",
      "chapterRange": "1-100",
      "coreFocus": "主角展现天赋，加入战队",
      "coreConflict": "替补/青训",
      "climax": "首次上场，惊艳表现"
    },
    {
      "title": "卷二：成长 (61-150章)",
      "chapterRange": "1-100",
      "coreFocus": "成为主力，参加联赛",
      "coreConflict": "主力选手",
      "climax": "联赛取得好成绩"
    },
    {
      "title": "卷三：崛起 (151-280章)",
      "chapterRange": "1-100",
      "coreFocus": "成为明星选手",
      "coreConflict": "一线选手",
      "climax": "获得联赛冠军"
    },
    {
      "title": "卷四：巅峰 (281-400章)",
      "chapterRange": "1-100",
      "coreFocus": "冲击世界赛",
      "coreConflict": "顶级选手",
      "climax": "世界赛夺冠"
    },
    {
      "title": "卷五：传奇 (401-500章)",
      "chapterRange": "1-100",
      "coreFocus": "成为传奇，功成身退",
      "coreConflict": "传奇选手",
      "climax": "圆满结局"
    }
  ],
  "pitfalls": [
    {
      "description": "Thiết lập trước sau mâu thuẫn.",
      "severity": "critical"
    }
  ],
  "bestPractices": [
    {
      "description": "Thiết lập tự nhất quán."
    }
  ],
  "entityTags": [
    {
      "type": "选手",
      "nameVi": "选手",
      "attributes": [
        "position",
        "team",
        "skill"
      ]
    },
    {
      "type": "战队",
      "nameVi": "战队",
      "attributes": [
        "rank",
        "roster"
      ]
    },
    {
      "type": "比赛",
      "nameVi": "比赛",
      "attributes": [
        "importance",
        "result"
      ]
    },
    {
      "type": "战术",
      "nameVi": "战术",
      "attributes": [
        "counter",
        "weakness"
      ]
    },
    {
      "type": "英雄/角色",
      "nameVi": "英雄/角色",
      "attributes": [
        "skill",
        "meta"
      ]
    }
  ],
  "constraintPacks": [
    "Pack M09",
    "Pack U03"
  ]
};
