/**
 * File: harem_family_template.ts
 * Purpose: Story template cho thể loại Đa Tử Đa Phúc / Hậu Cung Gia Đình
 * Layer: Data (Constants)
 * Domain: StoryTemplate
 * Deps: types/story_template
 * Generated by: scripts/convert_templates.ts
 */
import type { StoryTemplate } from '../../types/story_template';

export const HAREM_FAMILY_TEMPLATE: StoryTemplate = {
  "id": "harem-family",
  "name": "Đa Tử Đa Phúc / Hậu Cung Gia Đình",
  "originalName": "多子多福",
  "coreSellingPoint": "Thể loại đặc sắc.",
  "tags": [
    "harem",
    "family",
    "children"
  ],
  "subGenres": [
    {
      "name": "性格类型",
      "description": "类型 / 特点 / 攻略方式 ------ / ------ / ---------- 温柔型 / 善解人意、体贴 / 真诚、关心 活泼型 / 开朗、爱闹 / 陪玩、惊喜 冷艳型 / 高冷、傲娇 / 耐心、实力 腹黑型 / 聪明、有心机 / 智斗、征服 傲娇型 / 口是心非 / 坚持、戳穿",
      "coreAppeal": "类型 / 特点 / 攻略方式 ------ / ------ / ---------- 温柔型 / 善解人意、体贴 / 真诚、关心 活泼型 / 开朗、爱闹 / 陪玩、惊喜 冷艳型 / 高冷、傲娇 / 耐心、实力 腹黑型 / 聪明、有心机 / 智斗、征服 傲娇型 / 口是心非 / 坚持、戳穿"
    },
    {
      "name": "背景类型",
      "description": "类型 / 特点 / 剧情功能 ------ / ------ / ---------- 世家千金 / 资源、人脉 / 势力支持 江湖侠女 / 武力、正义 / 战斗辅助 异族公主 / 异域、神秘 / 世界扩展 平民女子 / 纯真、努力 / 情感共鸣 天才少女 / 智慧、能力 / 智囊辅助",
      "coreAppeal": "类型 / 特点 / 剧情功能 ------ / ------ / ---------- 世家千金 / 资源、人脉 / 势力支持 江湖侠女 / 武力、正义 / 战斗辅助 异族公主 / 异域、神秘 / 世界扩展 平民女子 / 纯真、努力 / 情感共鸣 天才少女 / 智慧、能力 / 智囊辅助"
    },
    {
      "name": "能力类型",
      "description": "类型 / 功能 / 子嗣加成 ------ / ------ / ---------- 战斗型 / 战斗力强 / 力量+敏捷 辅助型 / 治疗/增益 / 体质+精神 智谋型 / 策略/情报 / 智力+感知 特殊型 / 独特能力 / 特殊天赋 --",
      "coreAppeal": "类型 / 功能 / 子嗣加成 ------ / ------ / ---------- 战斗型 / 战斗力强 / 力量+敏捷 辅助型 / 治疗/增益 / 体质+精神 智谋型 / 策略/情报 / 智力+感知 特殊型 / 独特能力 / 特殊天赋 --"
    }
  ],
  "worldRules": [
    {
      "name": "背景选择",
      "description": "修仙世界 武侠江湖 异世大陆 都市异能 星际时代"
    },
    {
      "name": "势力设定",
      "description": "主角势力（从弱到强） 敌对势力（制造冲突） 中立势力（提供资源） 潜在盟友（后期助力） --"
    }
  ],
  "coolPatterns": [
    {
      "name": "系统爽点",
      "scenario": "**升级爽**: 等级提升 → 属性大幅增长 **抽奖爽**: 抽到稀有 → 获得强力道具/技能 **解锁爽**: 解锁新功能 → 系统升级 **成就爽**: 达成成就 → 丰厚奖励",
      "appeal": "**升级爽**: 等级提升 → 属性大幅增长 **抽奖爽**: 抽到稀有 → 获得强力道具/技能 **解锁爽**: 解锁新功能 → 系统升级 **成就爽**: 达成成就 → 丰厚奖励"
    },
    {
      "name": "后宫爽点",
      "scenario": "**攻略爽**: 好感度满 → 收入后宫 **吃醋爽**: 女主吃醋 → 情感满足 **争宠爽**: 女主争宠 → 被需要感 **齐心爽**: 后宫齐心 → 团队感",
      "appeal": "**攻略爽**: 好感度满 → 收入后宫 **吃醋爽**: 女主吃醋 → 情感满足 **争宠爽**: 女主争宠 → 被需要感 **齐心爽**: 后宫齐心 → 团队感"
    },
    {
      "name": "子嗣爽点",
      "scenario": "**出生爽**: 高品质子嗣 → 惊喜感 **成长爽**: 子嗣成才 → 成就感 **继承爽**: 能力继承 → 传承感 **逆袭爽**: 子嗣逆袭 → 骄傲感 --",
      "appeal": "**出生爽**: 高品质子嗣 → 惊喜感 **成长爽**: 子嗣成才 → 成就感 **继承爽**: 能力继承 → 传承感 **逆袭爽**: 子嗣逆袭 → 骄傲感 --"
    }
  ],
  "conflictPatterns": [
    {
      "type": "势力设定",
      "source": "主角势力（从弱到强） 敌对势力（制造冲突） 中立势力（提供资源） 潜在盟友（后期助力） --",
      "resolution": "主角势力（从弱到强） 敌对势力（制造冲突） 中立势力（提供资源） 潜在盟友（后期助力） --"
    }
  ],
  "outlineArcs": [
    {
      "title": "Quyển 1: Khởi Đầu",
      "chapterRange": "1-80",
      "coreFocus": "Giới thiệu thế giới.",
      "coreConflict": "Xung đột đầu tiên.",
      "climax": "Bước ngoặt."
    },
    {
      "title": "Quyển 2: Phát Triển",
      "chapterRange": "81-200",
      "coreFocus": "Mở rộng.",
      "coreConflict": "Xung đột chính.",
      "climax": "Đỉnh cao."
    },
    {
      "title": "Quyển 3: Kết Thúc",
      "chapterRange": "201-350",
      "coreFocus": "Giải quyết.",
      "coreConflict": "Đối đầu cuối.",
      "climax": "Viên mãn."
    }
  ],
  "pitfalls": [
    {
      "description": "Thiết lập trước sau mâu thuẫn.",
      "severity": "critical"
    }
  ],
  "bestPractices": [
    {
      "description": "Thiết lập tự nhất quán."
    }
  ],
  "entityTags": [
    {
      "type": "nhan_vat",
      "nameVi": "Nhân vật",
      "attributes": [
        "tính cách",
        "vai trò"
      ]
    }
  ],
  "constraintPacks": [
    "Pack F17",
    "Pack U03"
  ]
};
