/**
 * File: historical_template.ts
 * Purpose: Story template cho thể loại Lịch Sử Cổ Đại
 * Layer: Data (Constants)
 * Domain: StoryTemplate
 * Deps: types/story_template
 * Generated by: scripts/convert_templates.ts
 */
import type { StoryTemplate } from '../../types/story_template';

export const HISTORICAL_TEMPLATE: StoryTemplate = {
  "id": "historical",
  "name": "Lịch Sử Cổ Đại",
  "originalName": "历史古代",
  "coreSellingPoint": "大时代背景 + 权谋博弈 + 格局升级。在历史的洪流中，书写个人的传奇与时代的变迁。",
  "tags": [
    "historical",
    "ancient",
    "dynasty"
  ],
  "subGenres": [
    {
      "name": "Lịch Sử Cổ Đại",
      "description": "大时代背景 + 权谋博弈 + 格局升级。在历史的洪流中，书写个人的传奇与时代的变迁。",
      "coreAppeal": "大时代背景 + 权谋博弈 + 格局升级。在历史的洪流中，书写个人的传奇与时代的变迁。"
    }
  ],
  "worldRules": [],
  "coolPatterns": [],
  "conflictPatterns": [],
  "outlineArcs": [
    {
      "title": "卷一：入局 (1-80章)",
      "chapterRange": "1-100",
      "coreFocus": "主角进入历史舞台",
      "coreConflict": "底层/边缘",
      "climax": "初露锋芒，站稳脚跟"
    },
    {
      "title": "卷二：崛起 (81-200章)",
      "chapterRange": "1-100",
      "coreFocus": "积累实力，扩大影响",
      "coreConflict": "中层官员/地方势力",
      "climax": "获得重要职位/地盘"
    },
    {
      "title": "卷三：争锋 (201-400章)",
      "chapterRange": "1-100",
      "coreFocus": "与主要对手正面交锋",
      "coreConflict": "一方大员/诸侯",
      "climax": "击败主要对手"
    },
    {
      "title": "卷四：争霸 (401-600章)",
      "chapterRange": "1-100",
      "coreFocus": "逐鹿天下",
      "coreConflict": "顶级势力",
      "climax": "决定性战役/政变"
    },
    {
      "title": "卷五：定鼎 (601-700章)",
      "chapterRange": "1-100",
      "coreFocus": "统一/改革，建立新秩序",
      "coreConflict": "最高权力",
      "climax": "圆满结局"
    }
  ],
  "pitfalls": [
    {
      "description": "Thiết lập trước sau mâu thuẫn.",
      "severity": "critical"
    }
  ],
  "bestPractices": [
    {
      "description": "Thiết lập tự nhất quán."
    }
  ],
  "entityTags": [
    {
      "type": "势力",
      "nameVi": "势力",
      "attributes": [
        "territory",
        "military",
        "leader"
      ]
    },
    {
      "type": "官职",
      "nameVi": "官职",
      "attributes": [
        "rank",
        "power"
      ]
    },
    {
      "type": "人才",
      "nameVi": "人才",
      "attributes": [
        "loyalty",
        "history"
      ]
    },
    {
      "type": "战役",
      "nameVi": "战役",
      "attributes": [
        "result",
        "impact"
      ]
    },
    {
      "type": "政策",
      "nameVi": "政策",
      "attributes": [
        "effect",
        "opposition"
      ]
    }
  ],
  "languageRegister": {
    "eraLabel": "cổ đại / lịch sử / triều đại",
    "narrationStyle": "ngôi ba trang trọng, thiên sử khí, tôn ti rõ ràng; tránh lối nói hiện đại hóa nhân vật lịch sử",
    "hanVietDensity": "dense",
    "hanVietGuidance": "Dùng Hán Việt đậm ở chức vị, quân vụ, chính lệnh, địa danh; tránh khẩu ngữ thời nay trong quân thần và triều chính.",
    "dictionGuidance": "Chính sử, quyền mưu, chiến trận phải nhất quán ở register. Cùng một cảnh không đổi từ 'kinh thành' sang 'thành phố' hoặc 'chiếu chỉ' sang 'thông báo'.",
    "preferredTerms": [
      "kinh thành",
      "châu",
      "huyện",
      "biên thùy",
      "quân doanh",
      "chiếu chỉ"
    ],
    "avoidTerms": [
      "thành phố",
      "đơn vị hành chính hiện đại",
      "app",
      "startup",
      "CEO"
    ],
    "preferredPronouns": [
      "ta",
      "ngươi",
      "trẫm",
      "khanh",
      "thần",
      "mạt tướng"
    ],
    "forbiddenPronouns": [
      "tôi",
      "anh",
      "em",
      "bạn"
    ],
    "dialogueRules": [
      {
        "context": "quân thần",
        "preferredPairs": [
          "trẫm - khanh",
          "thần - bệ hạ"
        ],
        "forbiddenPairs": [
          "tôi - ông"
        ],
        "note": "Giữ đúng triều nghi."
      },
      {
        "context": "chiến trường, thị uy, hoặc giữ khoảng cách quyền lực",
        "preferredPairs": [
          "ta - ngươi",
          "bản tướng - ngươi"
        ],
        "forbiddenPairs": [
          "anh - tôi"
        ],
        "note": "\"Ta - ngươi\" có thể là địch ý, nhưng cũng có thể là thế trên-dưới hoặc cố tình giữ lạnh khoảng cách."
      }
    ]
  },
  "constraintPacks": [
    "Pack M08",
    "Pack U01"
  ]
};
