/**
 * File: livestream_template.ts
 * Purpose: Story template cho thể loại Trực Tiếp Văn / Livestream
 * Layer: Data (Constants)
 * Domain: StoryTemplate
 * Deps: types/story_template
 * Generated by: scripts/convert_templates.ts
 */
import type { StoryTemplate } from '../../types/story_template';

export const LIVESTREAM_TEMPLATE: StoryTemplate = {
  "id": "livestream",
  "name": "Trực Tiếp Văn / Livestream",
  "originalName": "直播文",
  "coreSellingPoint": "实时互动 + 舆论反转 + 商业变现。用“观众反馈”驱动剧情即时爽感。",
  "tags": [
    "livestream",
    "internet",
    "entertainment"
  ],
  "subGenres": [
    {
      "name": "Trực Tiếp Văn / Livestream",
      "description": "实时互动 + 舆论反转 + 商业变现。用“观众反馈”驱动剧情即时爽感。",
      "coreAppeal": "实时互动 + 舆论反转 + 商业变现。用“观众反馈”驱动剧情即时爽感。"
    }
  ],
  "worldRules": [],
  "coolPatterns": [],
  "conflictPatterns": [],
  "outlineArcs": [
    {
      "title": "卷一：起号 (1-60章)",
      "chapterRange": "1-100",
      "coreFocus": "完成账号定位，拿到第一波稳定观众",
      "coreConflict": "",
      "climax": "单场小爆发"
    },
    {
      "title": "卷二：破圈 (61-160章)",
      "chapterRange": "1-100",
      "coreFocus": "内容升级+平台推荐，进入竞争赛道",
      "coreConflict": "",
      "climax": "榜单逆袭"
    },
    {
      "title": "卷三：攻防 (161-300章)",
      "chapterRange": "1-100",
      "coreFocus": "应对黑粉、公关危机与团队矛盾",
      "coreConflict": "",
      "climax": "舆论反转战"
    },
    {
      "title": "卷四：商业化 (301-460章)",
      "chapterRange": "1-100",
      "coreFocus": "品牌合作、供应链、团队扩张",
      "coreConflict": "",
      "climax": "商业对赌胜出"
    },
    {
      "title": "卷五：新阶段 (461-620章)",
      "chapterRange": "1-100",
      "coreFocus": "从个人主播走向内容公司化",
      "coreConflict": "",
      "climax": "新赛道再封神"
    }
  ],
  "pitfalls": [
    {
      "description": "Thiết lập trước sau mâu thuẫn.",
      "severity": "critical"
    }
  ],
  "bestPractices": [
    {
      "description": "Thiết lập tự nhất quán."
    }
  ],
  "entityTags": [
    {
      "type": "主播",
      "nameVi": "主播",
      "attributes": [
        "track",
        "style"
      ]
    },
    {
      "type": "直播间",
      "nameVi": "直播间",
      "attributes": [
        "audience",
        "peak"
      ]
    },
    {
      "type": "品牌",
      "nameVi": "品牌",
      "attributes": [
        "budget",
        "relation"
      ]
    },
    {
      "type": "事件",
      "nameVi": "事件",
      "attributes": [
        "evidence",
        "impact"
      ]
    }
  ],
  "constraintPacks": [
    "Pack M08",
    "Pack U03"
  ]
};
