/**
 * File: melodrama_template.ts
 * Purpose: Story template cho thể loại Cẩu Huyết Ngôn Tình / Melodrama
 * Layer: Data (Constants)
 * Domain: StoryTemplate
 * Deps: types/story_template
 * Generated by: scripts/convert_templates.ts
 */
import type { StoryTemplate } from '../../types/story_template';

export const MELODRAMA_TEMPLATE: StoryTemplate = {
  "id": "melodrama",
  "name": "Cẩu Huyết Ngôn Tình / Melodrama",
  "originalName": "狗血言情",
  "coreSellingPoint": "情感冲突 + 虐恋情深 + 追妻火葬场。狗血不是贬义，是击中读者情感痛点的利器。",
  "tags": [
    "melodrama",
    "drama",
    "romance",
    "angst"
  ],
  "subGenres": [
    {
      "name": "Cẩu Huyết Ngôn Tình / Melodrama",
      "description": "情感冲突 + 虐恋情深 + 追妻火葬场。狗血不是贬义，是击中读者情感痛点的利器。",
      "coreAppeal": "情感冲突 + 虐恋情深 + 追妻火葬场。狗血不是贬义，是击中读者情感痛点的利器。"
    }
  ],
  "worldRules": [],
  "coolPatterns": [],
  "conflictPatterns": [],
  "outlineArcs": [
    {
      "title": "卷一：甜蜜假象 (1-50章, 15%)",
      "chapterRange": "1-100",
      "coreFocus": "卷一：甜蜜假象 (1-50章, 15%)",
      "coreConflict": "",
      "climax": ""
    },
    {
      "title": "卷二：虐心深渊 (51-130章, 25%)",
      "chapterRange": "1-100",
      "coreFocus": "卷二：虐心深渊 (51-130章, 25%)",
      "coreConflict": "",
      "climax": "小产/重病/被陷害"
    },
    {
      "title": "卷三：决裂离开 (131-180章, 15%)",
      "chapterRange": "1-100",
      "coreFocus": "卷三：决裂离开 (131-180章, 15%)",
      "coreConflict": "",
      "climax": ""
    },
    {
      "title": "卷四：追妻之路 (181-280章, 30%)",
      "chapterRange": "1-100",
      "coreFocus": "卷四：追妻之路 (181-280章, 30%)",
      "coreConflict": "",
      "climax": "女主有新欢，男主崩溃"
    },
    {
      "title": "卷五：破镜重圆 (281-350章, 15%)",
      "chapterRange": "1-100",
      "coreFocus": "卷五：破镜重圆 (281-350章, 15%)",
      "coreConflict": "",
      "climax": ""
    }
  ],
  "pitfalls": [
    {
      "description": "Thiết lập trước sau mâu thuẫn.",
      "severity": "critical"
    }
  ],
  "bestPractices": [
    {
      "description": "Thiết lập tự nhất quán."
    }
  ],
  "entityTags": [
    {
      "type": "情敌",
      "nameVi": "情敌",
      "attributes": [
        "rival_type",
        "ending"
      ]
    },
    {
      "type": "情感事件",
      "nameVi": "情感事件",
      "attributes": [
        "trigger"
      ]
    },
    {
      "type": "情侣状态",
      "nameVi": "情侣状态",
      "attributes": [
        "affection"
      ]
    }
  ],
  "constraintPacks": [
    "Pack F15",
    "Pack U01"
  ]
};
