/**
 * File: modern_brainwave_template.ts
 * Purpose: Story template cho thể loại Hiện Đại Ngôn Tình Não Động
 * Layer: Data (Constants)
 * Domain: StoryTemplate
 * Deps: types/story_template
 * Generated by: scripts/convert_templates.ts
 */
import type { StoryTemplate } from '../../types/story_template';

export const MODERN_BRAINWAVE_TEMPLATE: StoryTemplate = {
  "id": "modern-brainwave",
  "name": "Hiện Đại Ngôn Tình Não Động",
  "originalName": "现言脑洞",
  "coreSellingPoint": "现实关系 + 规则/异象 + 情感反转。当超自然规则入侵现代爱情，感情与规则如何共存？",
  "tags": [
    "modern-romance",
    "brainwave",
    "twist"
  ],
  "subGenres": [
    {
      "name": "Hiện Đại Ngôn Tình Não Động",
      "description": "现实关系 + 规则/异象 + 情感反转。当超自然规则入侵现代爱情，感情与规则如何共存？",
      "coreAppeal": "现实关系 + 规则/异象 + 情感反转。当超自然规则入侵现代爱情，感情与规则如何共存？"
    }
  ],
  "worldRules": [],
  "coolPatterns": [],
  "conflictPatterns": [],
  "outlineArcs": [
    {
      "title": "卷一：相遇 (1-50章)",
      "chapterRange": "1-100",
      "coreFocus": "因规则/能力相遇",
      "coreConflict": "",
      "climax": "发现规则/能力"
    },
    {
      "title": "卷二：相知 (51-120章)",
      "chapterRange": "1-100",
      "coreFocus": "在规则下相处",
      "coreConflict": "",
      "climax": "确认心意"
    },
    {
      "title": "卷三：考验 (121-200章)",
      "chapterRange": "1-100",
      "coreFocus": "规则与感情冲突",
      "coreConflict": "",
      "climax": "面临抉择"
    },
    {
      "title": "卷四：突破 (201-280章)",
      "chapterRange": "1-100",
      "coreFocus": "打破规则，选择真心",
      "coreConflict": "",
      "climax": "规则突破"
    },
    {
      "title": "卷五：圆满 (281-350章)",
      "chapterRange": "1-100",
      "coreFocus": "有情人终成眷属",
      "coreConflict": "",
      "climax": "圆满结局"
    }
  ],
  "pitfalls": [
    {
      "description": "Thiết lập trước sau mâu thuẫn.",
      "severity": "critical"
    }
  ],
  "bestPractices": [
    {
      "description": "Thiết lập tự nhất quán."
    }
  ],
  "entityTags": [
    {
      "type": "规则",
      "nameVi": "规则",
      "attributes": [
        "trigger",
        "loophole",
        "penalty"
      ]
    },
    {
      "type": "能力",
      "nameVi": "能力",
      "attributes": [
        "cost",
        "limit",
        "origin"
      ]
    },
    {
      "type": "关系",
      "nameVi": "关系",
      "attributes": [
        "rule",
        "stage"
      ]
    },
    {
      "type": "契约",
      "nameVi": "契约",
      "attributes": [
        "duration",
        "break"
      ]
    }
  ],
  "constraintPacks": [
    "Pack F03",
    "Pack U01"
  ]
};
