/**
 * File: palace_intrigue_template.ts
 * Purpose: Story template cho thể loại Cung Đấu / Trạch Đấu
 * Layer: Data (Constants)
 * Domain: StoryTemplate
 * Deps: types/story_template
 * Generated by: scripts/convert_templates.ts
 */
import type { StoryTemplate } from '../../types/story_template';

export const PALACE_INTRIGUE_TEMPLATE: StoryTemplate = {
  "id": "palace-intrigue",
  "name": "Cung Đấu / Trạch Đấu",
  "originalName": "宫斗宅斗",
  "coreSellingPoint": "规则博弈 + 心机对决 + 地位跃迁。在深宅大院中步步为营，用智慧改写命运。",
  "tags": [
    "palace",
    "intrigue",
    "politics",
    "female-lead"
  ],
  "subGenres": [
    {
      "name": "Cung Đấu / Trạch Đấu",
      "description": "规则博弈 + 心机对决 + 地位跃迁。在深宅大院中步步为营，用智慧改写命运。",
      "coreAppeal": "规则博弈 + 心机对决 + 地位跃迁。在深宅大院中步步为营，用智慧改写命运。"
    }
  ],
  "worldRules": [],
  "coolPatterns": [],
  "conflictPatterns": [],
  "outlineArcs": [
    {
      "title": "卷一：入局 (1-50章)",
      "chapterRange": "1-100",
      "coreFocus": "主角进入宫/府，了解规则",
      "coreConflict": "低位",
      "climax": "首次化解危机，站稳脚跟"
    },
    {
      "title": "卷二：立足 (51-120章)",
      "chapterRange": "1-100",
      "coreFocus": "建立关系网，获得初步地位",
      "coreConflict": "中低位",
      "climax": "击败第一个对手，小幅晋升"
    },
    {
      "title": "卷三：崛起 (121-200章)",
      "chapterRange": "1-100",
      "coreFocus": "卷入核心争斗",
      "coreConflict": "中位",
      "climax": "扳倒主要对手，大幅晋升"
    },
    {
      "title": "卷四：巅峰 (201-280章)",
      "chapterRange": "1-100",
      "coreFocus": "争夺最高位置",
      "coreConflict": "高位",
      "climax": "成为最终赢家"
    },
    {
      "title": "卷五：收尾 (281-350章)",
      "chapterRange": "1-100",
      "coreFocus": "处理遗留问题，结局",
      "coreConflict": "最高位",
      "climax": "圆满结局"
    }
  ],
  "pitfalls": [
    {
      "description": "Thiết lập trước sau mâu thuẫn.",
      "severity": "critical"
    }
  ],
  "bestPractices": [
    {
      "description": "Thiết lập tự nhất quán."
    }
  ],
  "entityTags": [
    {
      "type": "妃嫔",
      "nameVi": "妃嫔",
      "attributes": [
        "rank",
        "palace",
        "favor"
      ]
    },
    {
      "type": "势力",
      "nameVi": "势力",
      "attributes": [
        "power",
        "relation"
      ]
    },
    {
      "type": "事件",
      "nameVi": "事件",
      "attributes": [
        "result",
        "impact"
      ]
    },
    {
      "type": "关系",
      "nameVi": "关系",
      "attributes": [
        "status"
      ]
    },
    {
      "type": "秘密",
      "nameVi": "秘密",
      "attributes": [
        "danger",
        "usage"
      ]
    }
  ],
  "languageRegister": {
    "eraLabel": "cổ đại / cung đình / trạch đấu",
    "narrationStyle": "ngôi ba kín ý, hoa mỹ vừa phải, nhiều hàm ý và tầng nghĩa quyền lực",
    "hanVietDensity": "dense",
    "hanVietGuidance": "Danh xưng, vị phân, nghi thức nên dùng Hán Việt đậm và chính xác; không kéo khẩu ngữ hiện đại vào không gian hậu cung.",
    "dictionGuidance": "Hội thoại phải thể hiện rõ cấp bậc, ân sủng và địch ý. Khi ngoài mặt cung kính, lời vẫn cần giữ tầng ý chứ không thô hiện đại.",
    "preferredTerms": [
      "điện",
      "các",
      "nương nương",
      "thái giám",
      "vị phân",
      "sắc phong"
    ],
    "avoidTerms": [
      "thành phố",
      "căn hộ",
      "cao ốc",
      "app",
      "CEO"
    ],
    "preferredPronouns": [
      "bổn cung",
      "ngươi",
      "nô tỳ",
      "thần thiếp",
      "bệ hạ",
      "điện hạ"
    ],
    "forbiddenPronouns": [
      "tôi",
      "anh",
      "em",
      "bạn"
    ],
    "dialogueRules": [
      {
        "context": "hậu cung đấu đá",
        "preferredPairs": [
          "bổn cung - ngươi",
          "thần thiếp - bệ hạ"
        ],
        "forbiddenPairs": [
          "tôi - cô",
          "anh - em"
        ],
        "note": "Ngay cả khi mỉm cười, lời thoại vẫn phải giữ lễ và lưỡi dao giấu kín."
      },
      {
        "context": "chủ-tớ trong nội viện",
        "preferredPairs": [
          "nô tỳ - nương nương"
        ],
        "forbiddenPairs": [
          "tôi - chị"
        ],
        "note": "Khoảng cách địa vị phải thể hiện ngay từ cách xưng hô."
      }
    ]
  },
  "constraintPacks": [
    "Pack F05",
    "Pack U01"
  ]
};
