/**
 * File: realistic_template.ts
 * Purpose: Story template cho thể loại Hiện Thực Đề Tài
 * Layer: Data (Constants)
 * Domain: StoryTemplate
 * Deps: types/story_template
 * Generated by: scripts/convert_templates.ts
 */
import type { StoryTemplate } from '../../types/story_template';

export const REALISTIC_TEMPLATE: StoryTemplate = {
  "id": "realistic",
  "name": "Hiện Thực Đề Tài",
  "originalName": "现实题材",
  "coreSellingPoint": "真实感 + 社会共鸣 + 人性深度。扎根现实生活，引发读者强烈的代入感和情感共鸣。",
  "tags": [
    "realistic",
    "contemporary",
    "slice-of-life"
  ],
  "subGenres": [
    {
      "name": "职场奋斗流",
      "description": "职场升级打怪，事业与情感并行",
      "coreAppeal": "逆袭上位，打脸刁难者，事业爱情双丰收"
    },
    {
      "name": "婚恋生活流",
      "description": "婚姻家庭真实写照，情感纠葛",
      "coreAppeal": "渣男/渣女报应，真爱降临，幸福结局"
    },
    {
      "name": "逆袭成长流",
      "description": "底层人物奋斗史，命运抗争",
      "coreAppeal": "翻身逆袭，证明自我，实现梦想"
    },
    {
      "name": "家庭伦理流",
      "description": "家庭矛盾，亲情羁绊，人性考验",
      "coreAppeal": "矛盾化解，亲情回归，治愈人心"
    }
  ],
  "worldRules": [],
  "coolPatterns": [],
  "conflictPatterns": [
    {
      "type": "职场性别歧视",
      "source": "女主遭遇 → 抗争 → 改变",
      "resolution": "避免说教，用故事说话"
    },
    {
      "type": "原生家庭",
      "source": "父母PUA → 觉醒 → 边界建立",
      "resolution": "不妖魔化父母，展示复杂性"
    },
    {
      "type": "婚姻困境",
      "source": "丧偶式育儿/婆媳矛盾",
      "resolution": "不贩卖焦虑，给出出路"
    },
    {
      "type": "职场内卷",
      "source": "996/裁员/年龄歧视",
      "resolution": "有共鸣也要有希望"
    },
    {
      "type": "容貌焦虑",
      "source": "外貌评价 → 自我接纳",
      "resolution": "避免\"逆袭后打脸\"的单一模式"
    },
    {
      "type": "卷一：困境呈现 (1-50章, 20%)",
      "source": "职场/婚姻/家庭的困境",
      "resolution": "职场/婚姻/家庭的困境"
    },
    {
      "type": "卷二：挣扎觉醒 (51-130章, 30%)",
      "source": "**矛盾激化**: 困境加深，压力倍增 **认知转变**: 主角开始觉醒/改变 **能力积累**: 学习、成长、准备 **转折点**: 关键事件推动改变",
      "resolution": "**矛盾激化**: 困境加深，压力倍增 **认知转变**: 主角开始觉醒/改变 **能力积累**: 学习、成长、准备 **转折点**: 关键事件推动改变"
    },
    {
      "type": "卷三：奋力突围 (131-220章, 30%)",
      "source": "**行动展开**: 主动出击，改变现状 **遭遇阻碍**: 反对力量的阻挠 **贵人相助**: 关键助力出现 **高潮**: 决定性的胜利",
      "resolution": "**行动展开**: 主动出击，改变现状 **遭遇阻碍**: 反对力量的阻挠 **贵人相助**: 关键助力出现 **高潮**: 决定性的胜利"
    },
    {
      "type": "灰色人物设计",
      "source": "反派不是纯黑: 婆婆刁难，但是为了儿子 上司打压，但是自己也被压榨 渣男出轨，但是婚姻本就有问题 主角不是纯白: 有自私的一面 会犯错误 需要成长 --",
      "resolution": "反派不是纯黑: 婆婆刁难，但是为了儿子 上司打压，但是自己也被压榨 渣男出轨，但是婚姻本就有问题 主角不是纯白: 有自私的一面 会犯错误 需要成长 --"
    },
    {
      "type": "职场桥段",
      "source": "危机: 被新人抢功劳 被上司穿小鞋 遭遇职场性骚扰 35岁被优化 逆袭: 关键项目力挽狂澜 跳槽后碾压前东家 创业成功 曝光职场潜规则",
      "resolution": "危机: 被新人抢功劳 被上司穿小鞋 遭遇职场性骚扰 35岁被优化 逆袭: 关键项目力挽狂澜 跳槽后碾压前东家 创业成功 曝光职场潜规则"
    },
    {
      "type": "婚恋桥段",
      "source": "危机: 发现出轨证据 婆媳大战 丧偶式育儿 经济控制 觉醒: 决定离婚 经济独立 重新定义自我 遇到真爱",
      "resolution": "危机: 发现出轨证据 婆媳大战 丧偶式育儿 经济控制 觉醒: 决定离婚 经济独立 重新定义自我 遇到真爱"
    },
    {
      "type": "家庭桥段",
      "source": "冲突: 催婚/催生 偏心兄弟姐妹 父母PUA 经济纠纷 和解: 理解父母的局限 建立健康边界 选择性原谅 创造新的关系模式 --",
      "resolution": "冲突: 催婚/催生 偏心兄弟姐妹 父母PUA 经济纠纷 和解: 理解父母的局限 建立健康边界 选择性原谅 创造新的关系模式 --"
    }
  ],
  "outlineArcs": [
    {
      "title": "卷一：困境呈现 (1-50章, 20%)",
      "chapterRange": "1-50",
      "coreFocus": "**开篇钩子**: 展示主角当前困境 **人物登场**: 主角、对手、盟友、爱人 **核心矛盾**: 职场/婚姻/家庭的困境 **小高潮**: 第一次尝试突破（失败）",
      "coreConflict": "",
      "climax": ""
    },
    {
      "title": "卷二：挣扎觉醒 (51-130章, 30%)",
      "chapterRange": "51-130",
      "coreFocus": "**矛盾激化**: 困境加深，压力倍增 **认知转变**: 主角开始觉醒/改变 **能力积累**: 学习、成长、准备 **转折点**: 关键事件推动改变",
      "coreConflict": "",
      "climax": ""
    },
    {
      "title": "卷三：奋力突围 (131-220章, 30%)",
      "chapterRange": "131-220",
      "coreFocus": "**行动展开**: 主动出击，改变现状 **遭遇阻碍**: 反对力量的阻挠 **贵人相助**: 关键助力出现 **高潮**: 决定性的胜利",
      "coreConflict": "",
      "climax": "决定性的胜利"
    },
    {
      "title": "卷四：新生活 (221-280章, 20%)",
      "chapterRange": "221-280",
      "coreFocus": "**收获成果**: 事业/感情的圆满 **关系和解**: 与过去和解 **新的挑战**: 更高层次的追求 **结局**: 开放性或圆满结局 --",
      "coreConflict": "",
      "climax": ""
    }
  ],
  "targetWordCount": "600.000 chữ",
  "targetChapterCount": 280,
  "pitfalls": [
    {
      "description": "Thiết lập trước sau mâu thuẫn.",
      "severity": "critical"
    }
  ],
  "bestPractices": [
    {
      "description": "Thiết lập tự nhất quán."
    }
  ],
  "entityTags": [
    {
      "type": "社会议题",
      "nameVi": "社会议题",
      "attributes": [
        "attitude"
      ]
    },
    {
      "type": "现实场景",
      "nameVi": "现实场景",
      "attributes": [
        "emotion"
      ]
    },
    {
      "type": "职场",
      "nameVi": "职场",
      "attributes": [
        "industry"
      ]
    },
    {
      "type": "关系",
      "nameVi": "关系",
      "attributes": [
        "direction"
      ]
    }
  ],
  "constraintPacks": [
    "Pack M15",
    "Pack U02"
  ]
};
