/**
 * File: realistic_template.ts
 * Purpose: Story template cho thể loại Hiện Thực Đề Tài
 * Layer: Data (Constants)
 * Domain: StoryTemplate
 * Deps: types/story_template
 * Generated by: scripts/convert_templates.ts
 */
import type { StoryTemplate } from '../../types/story_template';

export const REALISTIC_TEMPLATE: StoryTemplate = {
  "id": "realistic",
  "name": "Hiện Thực Đề Tài",
  "originalName": "现实题材",
  "coreSellingPoint": "真实感 + 社会共鸣 + 人性深度。扎根现实生活，引发读者强烈的代入感和情感共鸣。",
  "tags": [
    "realistic",
    "contemporary",
    "slice-of-life"
  ],
  "subGenres": [
    {
      "name": "Hiện Thực Đề Tài",
      "description": "真实感 + 社会共鸣 + 人性深度。扎根现实生活，引发读者强烈的代入感和情感共鸣。",
      "coreAppeal": "真实感 + 社会共鸣 + 人性深度。扎根现实生活，引发读者强烈的代入感和情感共鸣。"
    }
  ],
  "worldRules": [],
  "coolPatterns": [],
  "conflictPatterns": [],
  "outlineArcs": [
    {
      "title": "卷一：困境呈现 (1-50章, 20%)",
      "chapterRange": "1-100",
      "coreFocus": "卷一：困境呈现 (1-50章, 20%)",
      "coreConflict": "",
      "climax": ""
    },
    {
      "title": "卷二：挣扎觉醒 (51-130章, 30%)",
      "chapterRange": "1-100",
      "coreFocus": "卷二：挣扎觉醒 (51-130章, 30%)",
      "coreConflict": "",
      "climax": ""
    },
    {
      "title": "卷三：奋力突围 (131-220章, 30%)",
      "chapterRange": "1-100",
      "coreFocus": "卷三：奋力突围 (131-220章, 30%)",
      "coreConflict": "",
      "climax": "决定性的胜利"
    },
    {
      "title": "卷四：新生活 (221-280章, 20%)",
      "chapterRange": "1-100",
      "coreFocus": "卷四：新生活 (221-280章, 20%)",
      "coreConflict": "",
      "climax": ""
    }
  ],
  "pitfalls": [
    {
      "description": "Thiết lập trước sau mâu thuẫn.",
      "severity": "critical"
    }
  ],
  "bestPractices": [
    {
      "description": "Thiết lập tự nhất quán."
    }
  ],
  "entityTags": [
    {
      "type": "社会议题",
      "nameVi": "社会议题",
      "attributes": [
        "attitude"
      ]
    },
    {
      "type": "现实场景",
      "nameVi": "现实场景",
      "attributes": [
        "emotion"
      ]
    },
    {
      "type": "职场",
      "nameVi": "职场",
      "attributes": [
        "industry"
      ]
    },
    {
      "type": "关系",
      "nameVi": "关系",
      "attributes": [
        "direction"
      ]
    }
  ],
  "constraintPacks": [
    "Pack M15",
    "Pack U02"
  ]
};
