/**
 * File: republic_romance_template.ts
 * Purpose: Story template cho thể loại Dân Quốc Ngôn Tình
 * Layer: Data (Constants)
 * Domain: StoryTemplate
 * Deps: types/story_template
 * Generated by: scripts/convert_templates.ts
 */
import type { StoryTemplate } from '../../types/story_template';

export const REPUBLIC_ROMANCE_TEMPLATE: StoryTemplate = {
  "id": "republic-romance",
  "name": "Dân Quốc Ngôn Tình",
  "originalName": "民国言情",
  "coreSellingPoint": "时代动荡 + 身份隐秘 + 爱恨纠葛。在乱世的风云中，书写刻骨铭心的爱情传奇。",
  "tags": [
    "republic-era",
    "romance",
    "historical"
  ],
  "subGenres": [
    {
      "name": "Dân Quốc Ngôn Tình",
      "description": "时代动荡 + 身份隐秘 + 爱恨纠葛。在乱世的风云中，书写刻骨铭心的爱情传奇。",
      "coreAppeal": "时代动荡 + 身份隐秘 + 爱恨纠葛。在乱世的风云中，书写刻骨铭心的爱情传奇。"
    }
  ],
  "worldRules": [],
  "coolPatterns": [],
  "conflictPatterns": [],
  "outlineArcs": [
    {
      "title": "卷一：相遇 (1-60章)",
      "chapterRange": "1-100",
      "coreFocus": "命运交织，情感萌芽",
      "coreConflict": "",
      "climax": "第一次心动"
    },
    {
      "title": "卷二：相知 (61-150章)",
      "chapterRange": "1-100",
      "coreFocus": "深入了解，感情升温",
      "coreConflict": "",
      "climax": "确认心意"
    },
    {
      "title": "卷三：考验 (151-250章)",
      "chapterRange": "1-100",
      "coreFocus": "家族/时代阻碍",
      "coreConflict": "",
      "climax": "被迫分离"
    },
    {
      "title": "卷四：守护 (251-350章)",
      "chapterRange": "1-100",
      "coreFocus": "为爱对抗一切",
      "coreConflict": "",
      "climax": "克服阻碍"
    },
    {
      "title": "卷五：圆满 (351-400章)",
      "chapterRange": "1-100",
      "coreFocus": "有情人终成眷属",
      "coreConflict": "",
      "climax": "圆满结局"
    }
  ],
  "pitfalls": [
    {
      "description": "Thiết lập trước sau mâu thuẫn.",
      "severity": "critical"
    }
  ],
  "bestPractices": [
    {
      "description": "Thiết lập tự nhất quán."
    }
  ],
  "entityTags": [
    {
      "type": "家族",
      "nameVi": "家族",
      "attributes": [
        "power",
        "tradition"
      ]
    },
    {
      "type": "身份",
      "nameVi": "身份",
      "attributes": [
        "public",
        "secret"
      ]
    },
    {
      "type": "关系",
      "nameVi": "关系",
      "attributes": [
        "obstacle",
        "stage"
      ]
    },
    {
      "type": "时代事件",
      "nameVi": "时代事件",
      "attributes": [
        "year",
        "impact"
      ]
    }
  ],
  "constraintPacks": [
    "Pack F10",
    "Pack U01"
  ]
};
