/**
 * File: short_fiction_template.ts
 * Purpose: Story template cho thể loại Đoản Thiên / Truyện Ngắn
 * Layer: Data (Constants)
 * Domain: StoryTemplate
 * Deps: types/story_template
 * Generated by: scripts/convert_templates.ts
 */
import type { StoryTemplate } from '../../types/story_template';

export const SHORT_FICTION_TEMPLATE: StoryTemplate = {
  "id": "short-fiction",
  "name": "Đoản Thiên / Truyện Ngắn",
  "originalName": "知乎短篇",
  "coreSellingPoint": "短平快 + 强冲突 + 极致反转。3000-15000字内完成起承转合，前300字定生死。",
  "tags": [
    "short-story",
    "flash-fiction"
  ],
  "subGenres": [
    {
      "name": "Đoản Thiên / Truyện Ngắn",
      "description": "短平快 + 强冲突 + 极致反转。3000-15000字内完成起承转合，前300字定生死。",
      "coreAppeal": "短平快 + 强冲突 + 极致反转。3000-15000字内完成起承转合，前300字定生死。"
    }
  ],
  "worldRules": [],
  "coolPatterns": [],
  "conflictPatterns": [],
  "outlineArcs": [
    {
      "title": "Quyển 1: Khởi Đầu",
      "chapterRange": "1-80",
      "coreFocus": "Giới thiệu thế giới.",
      "coreConflict": "Xung đột đầu tiên.",
      "climax": "Bước ngoặt."
    },
    {
      "title": "Quyển 2: Phát Triển",
      "chapterRange": "81-200",
      "coreFocus": "Mở rộng.",
      "coreConflict": "Xung đột chính.",
      "climax": "Đỉnh cao."
    },
    {
      "title": "Quyển 3: Kết Thúc",
      "chapterRange": "201-350",
      "coreFocus": "Giải quyết.",
      "coreConflict": "Đối đầu cuối.",
      "climax": "Viên mãn."
    }
  ],
  "pitfalls": [
    {
      "description": "Thiết lập trước sau mâu thuẫn.",
      "severity": "critical"
    }
  ],
  "bestPractices": [
    {
      "description": "Thiết lập tự nhất quán."
    }
  ],
  "entityTags": [
    {
      "type": "角色",
      "nameVi": "角色",
      "attributes": [
        "role"
      ]
    },
    {
      "type": "反转",
      "nameVi": "反转",
      "attributes": [
        "impact"
      ]
    },
    {
      "type": "钩子",
      "nameVi": "钩子",
      "attributes": [
        "emotion"
      ]
    }
  ],
  "constraintPacks": [
    "Pack M17",
    "Pack U02"
  ]
};
