/**
 * File: substitute_template.ts
 * Purpose: Story template cho thể loại Thế Thân Văn / Thay Thế
 * Layer: Data (Constants)
 * Domain: StoryTemplate
 * Deps: types/story_template
 * Generated by: scripts/convert_templates.ts
 */
import type { StoryTemplate } from '../../types/story_template';

export const SUBSTITUTE_TEMPLATE: StoryTemplate = {
  "id": "substitute",
  "name": "Thế Thân Văn / Thay Thế",
  "originalName": "替身文",
  "coreSellingPoint": "Thể loại đặc sắc.",
  "tags": [
    "substitute",
    "identity",
    "romance"
  ],
  "subGenres": [
    {
      "name": "Thế Thân Văn / Thay Thế",
      "description": "Thể loại đặc sắc.",
      "coreAppeal": "Thể loại đặc sắc."
    }
  ],
  "worldRules": [],
  "coolPatterns": [],
  "conflictPatterns": [],
  "outlineArcs": [
    {
      "title": "Quyển 1: Khởi Đầu",
      "chapterRange": "1-80",
      "coreFocus": "Giới thiệu thế giới.",
      "coreConflict": "Xung đột đầu tiên.",
      "climax": "Bước ngoặt."
    },
    {
      "title": "Quyển 2: Phát Triển",
      "chapterRange": "81-200",
      "coreFocus": "Mở rộng.",
      "coreConflict": "Xung đột chính.",
      "climax": "Đỉnh cao."
    },
    {
      "title": "Quyển 3: Kết Thúc",
      "chapterRange": "201-350",
      "coreFocus": "Giải quyết.",
      "coreConflict": "Đối đầu cuối.",
      "climax": "Viên mãn."
    }
  ],
  "pitfalls": [
    {
      "description": "Thiết lập trước sau mâu thuẫn.",
      "severity": "critical"
    }
  ],
  "bestPractices": [
    {
      "description": "Thiết lập tự nhất quán."
    }
  ],
  "entityTags": [
    {
      "type": "nhan_vat",
      "nameVi": "Nhân vật",
      "attributes": [
        "tính cách",
        "vai trò"
      ]
    }
  ],
  "constraintPacks": [
    "Pack F16",
    "Pack U01"
  ]
};
