/**
 * File: supernatural_mystery_template.ts
 * Purpose: Story template cho thể loại Huyền Nghi Linh Dị
 * Layer: Data (Constants)
 * Domain: StoryTemplate
 * Deps: types/story_template
 * Generated by: scripts/convert_templates.ts
 */
import type { StoryTemplate } from '../../types/story_template';

export const SUPERNATURAL_MYSTERY_TEMPLATE: StoryTemplate = {
  "id": "supernatural-mystery",
  "name": "Huyền Nghi Linh Dị",
  "originalName": "悬疑灵异",
  "coreSellingPoint": "氛围压迫 + 诡异规则 + 逻辑自洽。在恐惧与理性的边缘，探索未知的真相。",
  "tags": [
    "supernatural",
    "mystery",
    "ghost",
    "horror"
  ],
  "subGenres": [
    {
      "name": "Huyền Nghi Linh Dị",
      "description": "氛围压迫 + 诡异规则 + 逻辑自洽。在恐惧与理性的边缘，探索未知的真相。",
      "coreAppeal": "氛围压迫 + 诡异规则 + 逻辑自洽。在恐惧与理性的边缘，探索未知的真相。"
    }
  ],
  "worldRules": [],
  "coolPatterns": [],
  "conflictPatterns": [],
  "outlineArcs": [
    {
      "title": "卷一：入门 (1-50章)",
      "chapterRange": "1-100",
      "coreFocus": "主角接触灵异世界",
      "coreConflict": "初步觉醒",
      "climax": "首次解决灵异事件"
    },
    {
      "title": "卷二：成长 (51-150章)",
      "chapterRange": "1-100",
      "coreFocus": "能力提升，接触更多灵异",
      "coreConflict": "稳步提升",
      "climax": "解决重大灵异事件"
    },
    {
      "title": "卷三：深入 (151-250章)",
      "chapterRange": "1-100",
      "coreFocus": "探索灵异世界的真相",
      "coreConflict": "质变",
      "climax": "揭露部分真相"
    },
    {
      "title": "卷四：对抗 (251-350章)",
      "chapterRange": "1-100",
      "coreFocus": "与高级灵异对抗",
      "coreConflict": "接近巅峰",
      "climax": "击败主要敌人"
    },
    {
      "title": "卷五：终局 (351-400章)",
      "chapterRange": "1-100",
      "coreFocus": "最终真相，终极对决",
      "coreConflict": "巅峰",
      "climax": "圆满结局"
    }
  ],
  "pitfalls": [
    {
      "description": "Thiết lập trước sau mâu thuẫn.",
      "severity": "critical"
    }
  ],
  "bestPractices": [
    {
      "description": "Thiết lập tự nhất quán."
    }
  ],
  "entityTags": [
    {
      "type": "灵异",
      "nameVi": "灵异",
      "attributes": [
        "danger",
        "weakness",
        "origin"
      ]
    },
    {
      "type": "规则",
      "nameVi": "规则",
      "attributes": [
        "penalty",
        "loophole"
      ]
    },
    {
      "type": "能力",
      "nameVi": "能力",
      "attributes": [
        "cost",
        "limit"
      ]
    },
    {
      "type": "地点",
      "nameVi": "地点",
      "attributes": [
        "danger",
        "rule"
      ]
    }
  ],
  "constraintPacks": [
    "Pack M06",
    "Pack M07",
    "Pack U02"
  ]
};
