/**
 * File: sweet_youth_template.ts
 * Purpose: Story template cho thể loại Thanh Xuân Ngọt Sủng
 * Layer: Data (Constants)
 * Domain: StoryTemplate
 * Deps: types/story_template
 * Generated by: scripts/convert_templates.ts
 */
import type { StoryTemplate } from '../../types/story_template';

export const SWEET_YOUTH_TEMPLATE: StoryTemplate = {
  "id": "sweet-youth",
  "name": "Thanh Xuân Ngọt Sủng",
  "originalName": "青春甜宠",
  "coreSellingPoint": "轻甜氛围 + 高密度互动 + 成长共鸣。在最美好的年纪，遇见最对的人。",
  "tags": [
    "sweet",
    "youth",
    "school",
    "romance"
  ],
  "subGenres": [
    {
      "name": "Thanh Xuân Ngọt Sủng",
      "description": "轻甜氛围 + 高密度互动 + 成长共鸣。在最美好的年纪，遇见最对的人。",
      "coreAppeal": "轻甜氛围 + 高密度互动 + 成长共鸣。在最美好的年纪，遇见最对的人。"
    }
  ],
  "worldRules": [],
  "coolPatterns": [],
  "conflictPatterns": [],
  "outlineArcs": [
    {
      "title": "卷一：相遇 (1-50章)",
      "chapterRange": "1-100",
      "coreFocus": "男女主相识，建立联系",
      "coreConflict": "",
      "climax": "第一次心动瞬间"
    },
    {
      "title": "卷二：暧昧 (51-120章)",
      "chapterRange": "1-100",
      "coreFocus": "互动增多，暧昧升温",
      "coreConflict": "",
      "climax": "差点告白/被打断"
    },
    {
      "title": "卷三：确认 (121-180章)",
      "chapterRange": "1-100",
      "coreFocus": "告白成功，确定关系",
      "coreConflict": "",
      "climax": "正式告白，在一起"
    },
    {
      "title": "卷四：考验 (181-240章)",
      "chapterRange": "1-100",
      "coreFocus": "感情遇到考验",
      "coreConflict": "",
      "climax": "共同克服困难"
    },
    {
      "title": "卷五：圆满 (241-300章)",
      "chapterRange": "1-100",
      "coreFocus": "修成正果",
      "coreConflict": "",
      "climax": "甜蜜结局"
    }
  ],
  "pitfalls": [
    {
      "description": "Thiết lập trước sau mâu thuẫn.",
      "severity": "critical"
    }
  ],
  "bestPractices": [
    {
      "description": "Thiết lập tự nhất quán."
    }
  ],
  "entityTags": [
    {
      "type": "场景",
      "nameVi": "场景",
      "attributes": [
        "function",
        "memory"
      ]
    },
    {
      "type": "互动",
      "nameVi": "互动",
      "attributes": [
        "sweetness",
        "impact"
      ]
    },
    {
      "type": "事件",
      "nameVi": "事件",
      "attributes": [
        "emotion",
        "turning"
      ]
    },
    {
      "type": "关系",
      "nameVi": "关系",
      "attributes": [
        "stage",
        "obstacle"
      ]
    }
  ],
  "constraintPacks": [
    "Pack F06",
    "Pack U02"
  ]
};
