/**
 * File: system_flow_template.ts
 * Purpose: Story template cho thể loại Hệ Thống Lưu / System
 * Layer: Data (Constants)
 * Domain: StoryTemplate
 * Deps: types/story_template
 * Generated by: scripts/convert_templates.ts
 */
import type { StoryTemplate } from '../../types/story_template';

export const SYSTEM_FLOW_TEMPLATE: StoryTemplate = {
  "id": "system-flow",
  "name": "Hệ Thống Lưu / System",
  "originalName": "系统流",
  "coreSellingPoint": "数据可视化 + 任务驱动 + 确定性回报。系统是主角的最强外挂，但也可能是最大的枷锁。",
  "tags": [
    "system",
    "litrpg",
    "gamelit"
  ],
  "subGenres": [
    {
      "name": "Hệ Thống Lưu / System",
      "description": "数据可视化 + 任务驱动 + 确定性回报。系统是主角的最强外挂，但也可能是最大的枷锁。",
      "coreAppeal": "数据可视化 + 任务驱动 + 确定性回报。系统是主角的最强外挂，但也可能是最大的枷锁。"
    }
  ],
  "worldRules": [],
  "coolPatterns": [],
  "conflictPatterns": [],
  "outlineArcs": [
    {
      "title": "Quyển 1: Khởi Đầu",
      "chapterRange": "1-80",
      "coreFocus": "Giới thiệu thế giới.",
      "coreConflict": "Xung đột đầu tiên.",
      "climax": "Bước ngoặt."
    },
    {
      "title": "Quyển 2: Phát Triển",
      "chapterRange": "81-200",
      "coreFocus": "Mở rộng.",
      "coreConflict": "Xung đột chính.",
      "climax": "Đỉnh cao."
    },
    {
      "title": "Quyển 3: Kết Thúc",
      "chapterRange": "201-350",
      "coreFocus": "Giải quyết.",
      "coreConflict": "Đối đầu cuối.",
      "climax": "Viên mãn."
    }
  ],
  "pitfalls": [
    {
      "description": "Thiết lập trước sau mâu thuẫn.",
      "severity": "critical"
    }
  ],
  "bestPractices": [
    {
      "description": "Thiết lập tự nhất quán."
    }
  ],
  "entityTags": [
    {
      "type": "系统功能",
      "nameVi": "系统功能",
      "attributes": [
        "unlock"
      ]
    },
    {
      "type": "系统物品",
      "nameVi": "系统物品",
      "attributes": [
        "price"
      ]
    },
    {
      "type": "系统任务",
      "nameVi": "系统任务",
      "attributes": [
        "difficulty",
        "penalty"
      ]
    }
  ],
  "constraintPacks": [
    "Pack M13",
    "Pack M05",
    "Pack U03"
  ]
};
