/**
 * File: urban_daily_template.ts
 * Purpose: Story template cho thể loại Đô Thị Nhật Thường
 * Layer: Data (Constants)
 * Domain: StoryTemplate
 * Deps: types/story_template
 * Generated by: scripts/convert_templates.ts
 */
import type { StoryTemplate } from '../../types/story_template';

export const URBAN_DAILY_TEMPLATE: StoryTemplate = {
  "id": "urban-daily",
  "name": "Đô Thị Nhật Thường",
  "originalName": "都市日常",
  "coreSellingPoint": "真实生活感 + 小人物逆袭 + 细节共鸣。在平凡中书写不平凡，让读者看到自己的影子。",
  "tags": [
    "urban",
    "daily",
    "slice-of-life",
    "modern"
  ],
  "subGenres": [
    {
      "name": "Đô Thị Nhật Thường",
      "description": "真实生活感 + 小人物逆袭 + 细节共鸣。在平凡中书写不平凡，让读者看到自己的影子。",
      "coreAppeal": "真实生活感 + 小人物逆袭 + 细节共鸣。在平凡中书写不平凡，让读者看到自己的影子。"
    }
  ],
  "worldRules": [],
  "coolPatterns": [],
  "conflictPatterns": [],
  "outlineArcs": [
    {
      "title": "卷一：起步 (1-80章)",
      "chapterRange": "1-100",
      "coreFocus": "主角进入职场/开始创业",
      "coreConflict": "底层",
      "climax": "首次证明自己，获得认可"
    },
    {
      "title": "卷二：立足 (81-180章)",
      "chapterRange": "1-100",
      "coreFocus": "站稳脚跟，建立基础",
      "coreConflict": "基层",
      "climax": "首次晋升/项目成功"
    },
    {
      "title": "卷三：崛起 (181-300章)",
      "chapterRange": "1-100",
      "coreFocus": "快速上升，崭露头角",
      "coreConflict": "中层",
      "climax": "重大项目成功，进入核心圈"
    },
    {
      "title": "卷四：巅峰 (301-450章)",
      "chapterRange": "1-100",
      "coreFocus": "成为行业精英",
      "coreConflict": "高层",
      "climax": "达到事业巅峰"
    },
    {
      "title": "卷五：圆满 (451-550章)",
      "chapterRange": "1-100",
      "coreFocus": "人生圆满",
      "coreConflict": "顶层",
      "climax": "事业家庭双丰收"
    }
  ],
  "pitfalls": [
    {
      "description": "Thiết lập trước sau mâu thuẫn.",
      "severity": "critical"
    }
  ],
  "bestPractices": [
    {
      "description": "Thiết lập tự nhất quán."
    }
  ],
  "entityTags": [
    {
      "type": "公司",
      "nameVi": "公司",
      "attributes": [
        "scale",
        "culture"
      ]
    },
    {
      "type": "职位",
      "nameVi": "职位",
      "attributes": [
        "salary",
        "power"
      ]
    },
    {
      "type": "项目",
      "nameVi": "项目",
      "attributes": [
        "value",
        "difficulty"
      ]
    },
    {
      "type": "人脉",
      "nameVi": "人脉",
      "attributes": [
        "relation",
        "value"
      ]
    },
    {
      "type": "资产",
      "nameVi": "资产",
      "attributes": [
        "value",
        "source"
      ]
    }
  ],
  "constraintPacks": [
    "Pack M03",
    "Pack U02"
  ]
};
