/**
 * File: urban_superpower_template.ts
 * Purpose: Story template cho thể loại Đô Thị Dị Năng
 * Layer: Data (Constants)
 * Domain: StoryTemplate
 * Deps: types/story_template
 * Generated by: scripts/convert_templates.ts
 */
import type { StoryTemplate } from '../../types/story_template';

export const URBAN_SUPERPOWER_TEMPLATE: StoryTemplate = {
  "id": "urban-superpower",
  "name": "Đô Thị Dị Năng",
  "originalName": "都市异能",
  "coreSellingPoint": "熟悉的现代生活 + 超凡力量的入侵。在平凡中寻找非凡。",
  "tags": [
    "urban",
    "superpower",
    "awakening"
  ],
  "subGenres": [
    {
      "name": "Đô Thị Dị Năng",
      "description": "熟悉的现代生活 + 超凡力量的入侵。在平凡中寻找非凡。",
      "coreAppeal": "熟悉的现代生活 + 超凡力量的入侵。在平凡中寻找非凡。"
    }
  ],
  "worldRules": [],
  "coolPatterns": [],
  "conflictPatterns": [],
  "outlineArcs": [
    {
      "title": "Quyển 1: Khởi Đầu",
      "chapterRange": "1-80",
      "coreFocus": "Giới thiệu thế giới.",
      "coreConflict": "Xung đột đầu tiên.",
      "climax": "Bước ngoặt."
    },
    {
      "title": "Quyển 2: Phát Triển",
      "chapterRange": "81-200",
      "coreFocus": "Mở rộng.",
      "coreConflict": "Xung đột chính.",
      "climax": "Đỉnh cao."
    },
    {
      "title": "Quyển 3: Kết Thúc",
      "chapterRange": "201-350",
      "coreFocus": "Giải quyết.",
      "coreConflict": "Đối đầu cuối.",
      "climax": "Viên mãn."
    }
  ],
  "pitfalls": [
    {
      "description": "Thiết lập trước sau mâu thuẫn.",
      "severity": "critical"
    }
  ],
  "bestPractices": [
    {
      "description": "Thiết lập tự nhất quán."
    }
  ],
  "entityTags": [
    {
      "type": "异能",
      "nameVi": "异能",
      "attributes": [
        "level",
        "ability_type"
      ]
    },
    {
      "type": "组织",
      "nameVi": "组织",
      "attributes": [
        "leader",
        "danger"
      ]
    },
    {
      "type": "变异兽",
      "nameVi": "变异兽",
      "attributes": [
        "level",
        "habitat"
      ]
    }
  ],
  "constraintPacks": [
    "Pack M12",
    "Pack M05",
    "Pack U03"
  ]
};
