/**
 * File: war_espionage_template.ts
 * Purpose: Story template cho thể loại Kháng Chiến / Điệp Chiến
 * Layer: Data (Constants)
 * Domain: StoryTemplate
 * Deps: types/story_template
 * Generated by: scripts/convert_templates.ts
 */
import type { StoryTemplate } from '../../types/story_template';

export const WAR_ESPIONAGE_TEMPLATE: StoryTemplate = {
  "id": "war-espionage",
  "name": "Kháng Chiến / Điệp Chiến",
  "originalName": "抗战谍战",
  "coreSellingPoint": "身份博弈 + 信息战 + 高压生存。在敌后的刀锋上行走，用智慧与勇气守护信仰。",
  "tags": [
    "war",
    "espionage",
    "military",
    "spy"
  ],
  "subGenres": [
    {
      "name": "Kháng Chiến / Điệp Chiến",
      "description": "身份博弈 + 信息战 + 高压生存。在敌后的刀锋上行走，用智慧与勇气守护信仰。",
      "coreAppeal": "身份博弈 + 信息战 + 高压生存。在敌后的刀锋上行走，用智慧与勇气守护信仰。"
    }
  ],
  "worldRules": [],
  "coolPatterns": [],
  "conflictPatterns": [],
  "outlineArcs": [
    {
      "title": "卷一：潜入 (1-60章)",
      "chapterRange": "1-100",
      "coreFocus": "建立身份，站稳脚跟",
      "coreConflict": "边缘人员",
      "climax": "第一次重要任务"
    },
    {
      "title": "卷二：扎根 (61-150章)",
      "chapterRange": "1-100",
      "coreFocus": "深入敌营，获取信任",
      "coreConflict": "核心人员",
      "climax": "获取重要情报"
    },
    {
      "title": "卷三：危机 (151-250章)",
      "chapterRange": "1-100",
      "coreFocus": "身份受到怀疑",
      "coreConflict": "被调查",
      "climax": "化解危机"
    },
    {
      "title": "卷四：反击 (251-350章)",
      "chapterRange": "1-100",
      "coreFocus": "主动出击，打击敌人",
      "coreConflict": "关键棋子",
      "climax": "重大行动成功"
    },
    {
      "title": "卷五：胜利 (351-400章)",
      "chapterRange": "1-100",
      "coreFocus": "迎来胜利，身份揭晓",
      "coreConflict": "英雄",
      "climax": "圆满结局"
    }
  ],
  "pitfalls": [
    {
      "description": "Thiết lập trước sau mâu thuẫn.",
      "severity": "critical"
    }
  ],
  "bestPractices": [
    {
      "description": "Thiết lập tự nhất quán."
    }
  ],
  "entityTags": [
    {
      "type": "身份",
      "nameVi": "身份",
      "attributes": [
        "cover",
        "real",
        "risk"
      ]
    },
    {
      "type": "情报",
      "nameVi": "情报",
      "attributes": [
        "source",
        "destination"
      ]
    },
    {
      "type": "任务",
      "nameVi": "任务",
      "attributes": [
        "difficulty",
        "deadline"
      ]
    },
    {
      "type": "关系",
      "nameVi": "关系",
      "attributes": [
        "truth",
        "trust"
      ]
    }
  ],
  "constraintPacks": [
    "Pack M10",
    "Pack U02"
  ]
};
