/**
 * File: workplace_romance_template.ts
 * Purpose: Story template cho thể loại Chức Trường Hôn Luyến
 * Layer: Data (Constants)
 * Domain: StoryTemplate
 * Deps: types/story_template
 * Generated by: scripts/convert_templates.ts
 */
import type { StoryTemplate } from '../../types/story_template';

export const WORKPLACE_ROMANCE_TEMPLATE: StoryTemplate = {
  "id": "workplace-romance",
  "name": "Chức Trường Hôn Luyến",
  "originalName": "职场婚恋",
  "coreSellingPoint": "职场博弈 + 成长晋升 + 情感平衡。在事业与爱情的天平上，找到属于自己的平衡点。",
  "tags": [
    "workplace",
    "marriage",
    "romance",
    "modern"
  ],
  "subGenres": [
    {
      "name": "Chức Trường Hôn Luyến",
      "description": "职场博弈 + 成长晋升 + 情感平衡。在事业与爱情的天平上，找到属于自己的平衡点。",
      "coreAppeal": "职场博弈 + 成长晋升 + 情感平衡。在事业与爱情的天平上，找到属于自己的平衡点。"
    }
  ],
  "worldRules": [],
  "coolPatterns": [],
  "conflictPatterns": [],
  "outlineArcs": [
    {
      "title": "卷一：入职 (1-50章)",
      "chapterRange": "1-100",
      "coreFocus": "进入职场，适应环境",
      "coreConflict": "新人/底层",
      "climax": "第一个项目成功"
    },
    {
      "title": "卷二：成长 (51-120章)",
      "chapterRange": "1-100",
      "coreFocus": "能力提升，感情萌芽",
      "coreConflict": "骨干员工",
      "climax": "获得晋升机会"
    },
    {
      "title": "卷三：考验 (121-200章)",
      "chapterRange": "1-100",
      "coreFocus": "事业感情双重考验",
      "coreConflict": "中层管理",
      "climax": "度过危机"
    },
    {
      "title": "卷四：突破 (201-280章)",
      "chapterRange": "1-100",
      "coreFocus": "事业突破，感情确定",
      "coreConflict": "高层/合伙人",
      "climax": "事业巅峰"
    },
    {
      "title": "卷五：圆满 (281-350章)",
      "chapterRange": "1-100",
      "coreFocus": "事业爱情双丰收",
      "coreConflict": "行业精英",
      "climax": "圆满结局"
    }
  ],
  "pitfalls": [
    {
      "description": "Thiết lập trước sau mâu thuẫn.",
      "severity": "critical"
    }
  ],
  "bestPractices": [
    {
      "description": "Thiết lập tự nhất quán."
    }
  ],
  "entityTags": [
    {
      "type": "公司",
      "nameVi": "公司",
      "attributes": [
        "scale",
        "culture"
      ]
    },
    {
      "type": "职位",
      "nameVi": "职位",
      "attributes": [
        "rank",
        "salary"
      ]
    },
    {
      "type": "项目",
      "nameVi": "项目",
      "attributes": [
        "deadline",
        "stakeholder"
      ]
    },
    {
      "type": "关系",
      "nameVi": "关系",
      "attributes": [
        "workplace",
        "personal"
      ]
    }
  ],
  "constraintPacks": [
    "Pack F09",
    "Pack U02"
  ]
};
