/**
 * File: hierarchical_summary_cache.ts
 * Purpose: 3-tier Hierarchical Summary Cache (HSC) for long-range narrative memory.
 *          Tier 1: Chapter summaries (already generated by chapter_summary_generator)
 *          Tier 2: Arc summaries (aggregate 5-10 chapter summaries into 1 block)
 *          Tier 3: Global summary (aggregate all arc summaries into 1 compact block)
 * Layer: Memory → Infra
 * Domain: Narrative Memory
 * Deps: narrative_db (Dexie), token_estimator, story types
 *
 * Design: Deterministic aggregation by default (concatenate + truncate).
 *         No AI calls — keeps cost at zero. AI-enhanced mode deferred to future.
 */

import type { Project } from '../../types/story';
import type {
  CachedSummary,
  HscBuildOptions,
  HscContextBlock,
} from '../../types/summary_cache';
import {
  getSummaryCacheEntries,
  putSummaryCacheEntries,
  getSummaryCacheEntry,
} from '../../db/narrative_db';
import { quickTruncate, estimateTokens } from '../ai/token_estimator';
import { getChaptersChronological } from '../ai/surprise_engine';

// ─── Constants ───────────────────────────────────────────

const DEFAULT_ARC_BLOCK_SIZE = 10;
const DEFAULT_CHAPTER_MAX_CHARS = 150;
const DEFAULT_ARC_MAX_CHARS = 300;
const DEFAULT_GLOBAL_MAX_CHARS = 500;

// ─── Cache Key Builders ──────────────────────────────────

function buildCacheId(
  projectId: string,
  tier: CachedSummary['tier'],
  rangeKey: string
): string {
  return `${projectId}:${tier}:${rangeKey}`;
}

function hashSummaries(summaries: string[]): string {
  // [Domain:NarrativeMemory] Simple content hash for invalidation
  // Uses string length + first/last chars for fast comparison
  const combined = summaries.join('|');
  let hash = 0;
  for (let i = 0; i < combined.length; i++) {
    const char = combined.charCodeAt(i);
    hash = ((hash << 5) - hash + char) | 0;
  }
  return `h${Math.abs(hash).toString(36)}_${combined.length}`;
}

// ─── Tier 1: Chapter Summaries ───────────────────────────

/**
 * [Domain:NarrativeMemory] STEP 1 — Collect chapter-tier summaries.
 * Uses existing chapter.summary field (already populated by chapter_summary_generator).
 * Falls back to content truncation if summary is missing.
 */
function collectChapterSummaries(
  project: Project,
  maxChars: number
): Array<{ chapterIndex: number; summary: string }> {
  const chapters = getChaptersChronological(project);

  return chapters.map((chapter, index) => {
    const summary = chapter.summary
      ? quickTruncate(chapter.summary, maxChars)
      : quickTruncate(chapter.content, maxChars);

    return {
      chapterIndex: index + 1,
      summary,
    };
  });
}

// ─── Tier 2: Arc Summaries ───────────────────────────────

/**
 * [Domain:NarrativeMemory] STEP 2 — Build arc-level summary blocks.
 * Deterministic: concatenates chapter summaries within each block range,
 * then truncates to arcMaxChars. Zero AI cost.
 */
function buildArcSummaryText(
  chapterSummaries: Array<{ chapterIndex: number; summary: string }>,
  startIndex: number,
  endIndex: number,
  arcMaxChars: number
): string {
  const block = chapterSummaries.filter(
    (cs) => cs.chapterIndex >= startIndex && cs.chapterIndex <= endIndex
  );

  if (block.length === 0) return '';

  // Condensed format: "Ch.1-5: event1. event2. event3."
  const condensed = block
    .map((cs) => `Ch.${cs.chapterIndex}: ${cs.summary}`)
    .join(' | ');

  return quickTruncate(condensed, arcMaxChars);
}

// ─── Tier 3: Global Summary ─────────────────────────────

/**
 * [Domain:NarrativeMemory] STEP 3 — Build global summary from arc blocks.
 * Deterministic: concatenates arc summaries, then truncates to globalMaxChars.
 */
function buildGlobalSummaryText(
  arcSummaries: Array<{ rangeKey: string; summary: string }>,
  globalMaxChars: number
): string {
  if (arcSummaries.length === 0) return '';

  const condensed = arcSummaries
    .map((arc) => `[${arc.rangeKey}] ${arc.summary}`)
    .join(' ');

  return quickTruncate(condensed, globalMaxChars);
}

// ─── Main Build Function ─────────────────────────────────

/**
 * [Domain:NarrativeMemory] STEP 4 — Rebuild HSC for a project.
 * Only rebuilds tiers that have changed (hash-based invalidation).
 * Returns number of entries updated.
 */
export async function rebuildHsc(
  project: Project,
  options?: HscBuildOptions
): Promise<number> {
  const arcBlockSize = options?.arcBlockSize ?? DEFAULT_ARC_BLOCK_SIZE;
  const chapterMaxChars = options?.chapterMaxChars ?? DEFAULT_CHAPTER_MAX_CHARS;
  const arcMaxChars = options?.arcMaxChars ?? DEFAULT_ARC_MAX_CHARS;
  const globalMaxChars = options?.globalMaxChars ?? DEFAULT_GLOBAL_MAX_CHARS;

  const now = new Date().toISOString();
  const chapterSummaries = collectChapterSummaries(project, chapterMaxChars);
  const totalChapters = chapterSummaries.length;

  if (totalChapters === 0) return 0;

  const entriesToStore: CachedSummary[] = [];
  const arcBlocks: Array<{ rangeKey: string; summary: string }> = [];

  // Build Tier 2: Arc summaries in blocks of arcBlockSize
  for (let start = 1; start <= totalChapters; start += arcBlockSize) {
    const end = Math.min(start + arcBlockSize - 1, totalChapters);
    const rangeKey = `${start}-${end}`;
    const cacheId = buildCacheId(project.id, 'arc', rangeKey);

    // Source hash from chapter summaries in this range
    const sourceSummaries = chapterSummaries
      .filter((cs) => cs.chapterIndex >= start && cs.chapterIndex <= end)
      .map((cs) => cs.summary);
    const sourceHash = hashSummaries(sourceSummaries);

    // Check if existing cache is still valid
    const existing = await getSummaryCacheEntry(cacheId);
    if (existing && existing.sourceHash === sourceHash) {
      arcBlocks.push({ rangeKey, summary: existing.summary });
      continue;
    }

    // Rebuild arc summary
    const summary = buildArcSummaryText(chapterSummaries, start, end, arcMaxChars);
    if (!summary) continue;

    arcBlocks.push({ rangeKey, summary });
    entriesToStore.push({
      id: cacheId,
      projectId: project.id,
      tier: 'arc',
      rangeKey,
      summary,
      chapterStart: start,
      chapterEnd: end,
      sourceHash,
      sourceCount: sourceSummaries.length,
      createdAt: existing?.createdAt ?? now,
      updatedAt: now,
    });
  }

  // Build Tier 3: Global summary from all arc blocks
  if (arcBlocks.length > 0) {
    const globalRangeKey = 'all';
    const globalCacheId = buildCacheId(project.id, 'global', globalRangeKey);
    const globalSourceHash = hashSummaries(arcBlocks.map((ab) => ab.summary));

    const existingGlobal = await getSummaryCacheEntry(globalCacheId);
    if (!existingGlobal || existingGlobal.sourceHash !== globalSourceHash) {
      const globalSummary = buildGlobalSummaryText(arcBlocks, globalMaxChars);
      if (globalSummary) {
        entriesToStore.push({
          id: globalCacheId,
          projectId: project.id,
          tier: 'global',
          rangeKey: globalRangeKey,
          summary: globalSummary,
          chapterStart: 1,
          chapterEnd: totalChapters,
          sourceHash: globalSourceHash,
          sourceCount: arcBlocks.length,
          createdAt: existingGlobal?.createdAt ?? now,
          updatedAt: now,
        });
      }
    }
  }

  // Persist only changed entries
  if (entriesToStore.length > 0) {
    await putSummaryCacheEntries(entriesToStore);
  }

  return entriesToStore.length;
}

// ─── Context Retrieval ───────────────────────────────────

/**
 * [Domain:NarrativeMemory] STEP 5 — Retrieve long-range memory for context injection.
 * Strategy for Ch.N:
 *   - Global summary (Tier 3) for whole-story awareness
 *   - Arc summaries (Tier 2) for chapters 1 through (N - arcBlockSize)
 *   - Recent chapters (Tier 1) already handled by context_builder's sliding window
 *
 * @param maxChars — total char budget for HSC block
 */
export async function retrieveHscContext(
  projectId: string,
  targetChapterIndex: number,
  maxChars = 1500
): Promise<HscContextBlock | null> {
  // Only inject long-range memory if we have enough chapters
  if (targetChapterIndex < 10) return null;

  const allEntries = await getSummaryCacheEntries(projectId);
  if (allEntries.length === 0) return null;

  const globalEntry = allEntries.find((e) => e.tier === 'global');
  const arcEntries = allEntries
    .filter((e) => e.tier === 'arc')
    .sort((a, b) => a.chapterStart - b.chapterStart);

  // [Domain:ContextSelection] Only include arc summaries for chapters
  // before the sliding window (last 5 chapters handled by Board 2)
  const longRangeCutoff = Math.max(1, targetChapterIndex - 5);
  const relevantArcs = arcEntries.filter((e) => e.chapterEnd <= longRangeCutoff);

  if (relevantArcs.length === 0 && !globalEntry) return null;

  const parts: string[] = [];
  const tiersUsed: HscContextBlock['tiersUsed'] = [];
  let remainingBudget = maxChars;
  let coverageStart = 1;
  let coverageEnd = longRangeCutoff;

  // Tier 3: Global overview first (cheapest, broadest coverage)
  if (globalEntry && globalEntry.summary.length <= remainingBudget * 0.4) {
    parts.push(`[HSC:GLOBAL] ${globalEntry.summary}`);
    remainingBudget -= globalEntry.summary.length + 14;
    tiersUsed.push('global');
  }

  // Tier 2: Arc details for uncovered range
  if (relevantArcs.length > 0 && remainingBudget > 100) {
    const arcLines: string[] = [];
    for (const arc of relevantArcs) {
      const line = `[Ch.${arc.chapterStart}-${arc.chapterEnd}] ${arc.summary}`;
      if (arcLines.join('\n').length + line.length > remainingBudget) break;
      arcLines.push(line);
    }
    if (arcLines.length > 0) {
      parts.push(arcLines.join('\n'));
      tiersUsed.push('arc');
      coverageEnd = relevantArcs[Math.min(arcLines.length - 1, relevantArcs.length - 1)].chapterEnd;
    }
  }

  if (parts.length === 0) return null;

  const text = `## BỘ NHỚ DÀI HẠN (Long-Range Memory)\n${parts.join('\n')}`;

  return {
    text,
    tokenEstimate: estimateTokens(text),
    tiersUsed,
    coverageRange: { start: coverageStart, end: coverageEnd },
  };
}
