ALTER TABLE public.characters
  ADD COLUMN IF NOT EXISTS core_wound TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS deep_fear TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS hidden_desire TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS self_deception TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS body_language TEXT DEFAULT '';
